.dumi/theme/locales/en-US.json
.dumi/theme/locales/zh-CN.json
scripts/remove-useless-locale.ts

- `scripts/remove-useless-locale.ts` excludes some keys as below:
- app.docs.components.icon.category.direction
- app.docs.components.icon.category.suggestion
- app.docs.components.icon.category.editor
- app.docs.components.icon.category.data
- app.docs.components.icon.category.other
- app.docs.components.icon.category.logo

fix(site): Add missing locale text

---

packages/ui/src/Action/Item.tsx

- `Action.Button` works correctly.
- `Action.Link` works fine.

fix(Action): should loading only when enableLoading and return promise

---

packages/ui/src/_util/useHistory.ts

- react-router-dom v5: `useHistory`
- react-router-dom v6: `useNavigate`
- by default without react-router-dom: `directTo`

feat(ui): custom useHistory support for react-router-dom v5

---

.dumi/theme/slots/Sidebar/index.tsx

| Previous | After |
| --- | --- |
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/f66bd222-da9f-4e8d-a6a2-1ae679cf760f)  |    ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/428a508c-e08d-468d-8e1e-51645740b03a) |

fix(site): sidebar background should be correct in dark mode

---

packages/design/src/alert/demo/action.tsx
packages/design/src/alert/demo/over-length.tsx
packages/design/src/alert/index.md
packages/design/src/alert/style/index.ts

- when `message` is over length, icon and close icon should vertical align to `flex-start`:
| Previous | After |
| --- | --- |
|  ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/82916d98-dd83-4977-b42d-92cff06cd991) |  ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/93449a72-0533-40e8-8f34-9ae68261044a) |
|  ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/79c49939-e6d6-409a-b1cd-d00a51601faa) |  ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/f12a05d5-dca6-4f44-a0ed-2b3af0b5c61a)  |

improve(design): Icon and close icon should vertical align to flex-start

---

.dumirc.ts
packages/charts/src/Score/demo/basic.tsx
packages/charts/src/Score/demo/custom.tsx
packages/charts/src/Score/demo/customColor.tsx
packages/charts/src/Score/demo/customThreshold.tsx
packages/charts/src/Score/index.less
packages/charts/src/Score/index.md
packages/charts/src/Score/index.tsx
packages/charts/src/Stat/demo/basic.tsx
packages/charts/src/index.ts

新增 Score 得分图组件, 主要用于突出展示一个数值分数的动态效果。
- 默认 85 <= num 分为优（绿色），70 <= num < 85 为良（蓝色），60 <= num < 70 为中（橙色），NUM < 60 为差（红色）
- 支持自定义单位、数值样式、单位样式、阈值配置等。
| 参数       | 说明                 | 类型            | 默认值 | 版本 |
| :--------- | :------------------- | :-------------- | :----- | :--- |
| size       | 图表大小             | string\| number | middle | -    |
| color      | 图表颜色             | string          | green  | -    |
| value      | 数值                 | number          | -      | -    |
| valueStyle | 数字样式             | CSSProperties   | -      | -    |
| unit       | 单位                 | string          | 分     | -    |
| unitStyle  | 单位样式             | CSSProperties   | -      | -    |
| thresholds | 阈值和颜色值映射对象 | object          | -      | -    |
| className  | 类名                 | string …

feat(charts): Add Score component

---

packages/design/src/spin/style/index.ts

fix(design): genSizeStyle should cover default style for Spin

---

packages/design/src/config-provider/__tests__/__snapshots__/spin.test.tsx.snap
packages/design/src/config-provider/__tests__/navigate.test.tsx
packages/design/src/config-provider/__tests__/spin.test.tsx
packages/design/src/config-provider/index.tsx

- Close #123.
- `navigate` should inherit from parent ConfigProvider.

fix(design): navigate should work in nested ConfigProvider

---

packages/design/src/button/style/index.ts
packages/design/src/card/style/index.ts
packages/design/src/descriptions/style/index.ts
packages/design/src/modal/__tests__/__snapshots__/progress.test.tsx.snap
packages/design/src/table/style/index.ts
packages/ui/src/BasicLayout/style/index.ts
packages/ui/src/PageContainer/style/index.ts
packages/ui/src/TagSelect/style/index.ts

https://github.com/oceanbase/oceanbase-design/actions/runs/6158919157/job/16712672298

fix(design & ui): TS type error for component token

---

packages/charts/src/Area/index.tsx
packages/charts/src/Bar/index.tsx
packages/charts/src/Column/index.tsx
packages/charts/src/DualAxes/index.tsx
packages/charts/src/Gauge/index.tsx
packages/charts/src/Histogram/index.tsx
packages/charts/src/Line/index.tsx
packages/charts/src/Liquid/index.tsx
packages/charts/src/Pie/demo/state-change.tsx
packages/charts/src/Pie/index.md
packages/charts/src/Pie/index.tsx
packages/charts/src/Tiny/Progress.tsx
packages/charts/src/Tiny/TinyArea.tsx
packages/charts/src/Tiny/TinyColumn.tsx
packages/charts/src/Tiny/TinyLine.tsx
packages/charts/src/util/custom-memo.ts

- Add `customMemo` wrapper with deep comparison for charts based on `@ant-design/charts` to avoid re-render when state change.

feat(charts): Add customMemo wrapper for charts based on @ant-design/charts

---

package.json
packages/charts/src/Pie/demo/state-change.tsx
packages/charts/src/util/__tests__/custom-memo.test.ts
packages/charts/src/util/custom-memo.ts
packages/design/src/index.ts
packages/ui/src/SideTip/demo/content.tsx
pnpm-lock.yaml

- Ref: #151.
- There is no need to add `useCallback` wrapper for `function` prop from now on.

feat(charts): customMemo support to compare function

---

packages/ui/src/BasicLayout/index.tsx
packages/ui/src/BasicLayout/style/index.ts
packages/ui/src/PageContainer/demo/empty.tsx

- With sider:
- With sider and sub sider:
- Without sider:

improve(ui): PageContainer footer bar width adapt to sider width of BasicLayout

---

packages/design/src/table/demo/bordered.tsx
packages/design/src/table/index.md
packages/design/src/table/style/index.ts

| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/c7b5d873-0689-427f-af65-353caf9c520b) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/c10ce061-b12f-41b3-9045-1ffaa03a6c57) |

improve(design): Remove pagination borderTop for bordered Table

---

packages/ui/src/BasicLayout/demo/menu-over-length.tsx
packages/ui/src/BasicLayout/index.md
packages/ui/src/BasicLayout/index.tsx
packages/ui/src/BasicLayout/style/Header.ts
packages/ui/src/Welcome/index.less
packages/ui/src/Welcome/index.tsx

- BasicLayout style with Welcome:
- BasicLayout style with dark theme:
- BasicLayout style with over-length menu:

improve(ui): BasicLayout style with Welcome, dark theme and over-length menu

---

packages/codemod/README.md
packages/codemod/transforms/__testfixtures__/less-to-token/antd-v4-less-to-token.input.less
packages/codemod/transforms/__testfixtures__/less-to-token/antd-v4-less-to-token.output.less
packages/codemod/transforms/__testfixtures__/less-to-token/obui-less-to-token.input.less
packages/codemod/transforms/__testfixtures__/less-to-token/obui-less-to-token.output.less
packages/codemod/transforms/__testfixtures__/style-to-token/class-component.input.js
packages/codemod/transforms/__testfixtures__/style-to-token/class-component.output.js
packages/codemod/transforms/__testfixtures__/style-to-token/function-component.input.js
packages/codemod/transforms/__testfixtures__/style-to-token/function-component.output.js
packages/codemod/transforms/__testfixtures__/style-to-token/static.input.js
packages/codemod/transforms/__testfixtures__/style-to-token/static.output.js
packages/codemod/transforms/less-to-token.js
packages/codemod/transforms/style-to-token.js
packages/codemod/transforms/utils/token.js

- Ref: #60
- `style-to-token` transform:
```diff
import React from 'react';
- import { Alert, Button } from '@oceanbase/design';
+ import { Alert, Button, theme } from '@oceanbase/design';
const Demo = () => {
+   const { token } = theme.useToken();
return (
-     <div>
-       <Alert style={{ border: '1px solid #d9d9d9' }} />
-     </div>
+     (<div>
+       <Alert style={{ border: `1px solid ${token.colorBorder}` }} />
+     </div>)
);
};
export default Demo;
```
- `less-to-token` transform:
```diff
+ @import '~@oceanbase/design/es/theme/index.less';
.container {
.content {
-     border: 1px solid #d9d9d9;
+     border: 1px solid @colorBorder;
}
}
```

feat(codemod): Support fuzzy matching for style-to-token and less-to-token transform

---

docs/codemod/codemod-CHANGELOG.md
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2023-10-26`
- Table
- 🐞 修复 `columns` 为空时，Table 执行报错、导致页面白屏的问题。[#206](https://github.com/oceanbase/oceanbase-design/pull/206)
- 💄 优化带边框的 Table 样式，去掉其底部多余的 border。[#207](https://github.com/oceanbase/oceanbase-design/pull/207)
`2023-10-26`
- BasicLayout
- 🔥 样式方案从 less 改造为 CSS-in-JS，以支持动态主题。[#201](https://github.com/oceanbase/oceanbase-design/pull/201) [@Vanleehao](https://github.com/Vanleehao)
- 🆕 菜单项超长支持自动省略，并展示 tooltip 提示。[#208](https://github.com/oceanbase/oceanbase-design/pull/208)
- 💄 适配暗色主题。[#208](https://github.com/oceanbase/oceanbase-design/pull/208)
- 💄 优化和 Welcome 组合使用的样式效果。[#208](https://github.com/oceanbase/oceanbase-design/pull/208)
- 💄 PageContainer 适配 pro-components 的最新版本，优化页头和面包屑导航的样式。[#209](https://github.com/oceanbase/oceanbase-design/pull/209)
`2023-10-26`
- 🔥 新增 …

chore(docs): Add changelog for @oceanbase/design@0.2.24, @oceanbase/ui@0.2.25 and @oceanbase/codemod@0.2.7

---

packages/design/src/tooltip/__tests__/index.test.tsx
packages/design/src/tooltip/demo/close-icon.tsx
packages/design/src/tooltip/index.tsx

| ![2023-10-29 17-00-24 2023-10-29 17_01_18](https://github.com/oceanbase/oceanbase-design/assets/14918822/a9bbb1b1-9d28-400e-a19f-818703ae903b)  |  ![2023-10-29 16-57-00 2023-10-29 16_58_10](https://github.com/oceanbase/oceanbase-design/assets/14918822/c8d854b7-ed42-4d8f-9684-a1dc3995f224) |

fix(design): Tooltip closeIcon should consider visible prop

---

packages/codemod/bin/cli.js

fix(codemod): path => targetPath to avoid duplicate name when prettier

---

packages/codemod/transforms/__testfixtures__/style-to-token/function-component.input.js
packages/codemod/transforms/__testfixtures__/style-to-token/function-component.output.js
packages/codemod/transforms/utils/token.js

- None
- includes => more match conditions for `tokenParse`:
| 🇺🇸 English |  🐞 Fix incorrect rewritten token resulted by loose style match condition. [#238](https://github.com/oceanbase/oceanbase-design/pull/238)       |
| 🇨🇳 Chinese | 🐞 修复样式匹配规则不严谨导致 token 改写错误的问题。[#238](https://github.com/oceanbase/oceanbase-design/pull/238)          |

fix(codemod): includes => more match conditions for tokenParse

---

packages/codemod/transforms/less-to-token.js

| 🇺🇸 English |  🐞 Fix `less-to-style` should not transform single non less file. [#242](https://github.com/oceanbase/oceanbase-design/pull/242)        |
| 🇨🇳 Chinese |  🐞 修复 `less-to-style` 不应该转换单个非 less 文件的问题。[#242](https://github.com/oceanbase/oceanbase-design/pull/242)         |

fix(codemod): should not transform when specific file is not .less

---

packages/ui/src/PageContainer/style/index.ts

- None
- PageContainer header related style should work.
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/af33f499-8c38-4e61-839a-e6a512c58345) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/11bf1965-12d7-4648-9175-b623c17a2521) |
| 🇺🇸 English |  🐞 Fix PageContainer header related style should work. [#254](https://github.com/oceanbase/oceanbase-design/pull/254)        |
| 🇨🇳 Chinese | 🐞 修复 PageContainer 页头相关样式不生效的问题。[#254](https://github.com/oceanbase/oceanbase-design/pull/254)          |

fix(ui): PageContainer header related style should work

---

docs/codemod/codemod-CHANGELOG.md
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2023-10-31`
- 🔥 新增 Tag 组件，优化 border 样式以弱化边框，内容超长支持自动省略，可通过 `ellipsis` 属性进行控制。[#113](https://github.com/oceanbase/oceanbase-design/pull/113) [@wdyea-ya](https://github.com/wdyea-ya)
- 🐞 修复 Tooltip 未兼容 `visible` 属性导致显示和隐藏无法受控的问题。[#231](https://github.com/oceanbase/oceanbase-design/pull/231)
`2023-10-31`
- 🆕 BackgroundTaskManager 消息通知增加唯一 key，并透出 `closeNotification` 接口用于手动关闭。[#239](https://github.com/oceanbase/oceanbase-design/pull/239) [@Qiuhang817385](https://github.com/Qiuhang817385)
- 🐞 修复 PageContainer 页头相关样式不生效的问题。[#254](https://github.com/oceanbase/oceanbase-design/pull/254)
- 🐞 修复 BasicLayout 顶部语言切换的字体大小偏大的问题。[#255](https://github.com/oceanbase/oceanbase-design/pull/255)
`2023-10-31`
- 📖 新增 `@oceanbase/design`、`@oceanbase/ui` 和 `@oceanbase/charts` 基于 @oceanbase/codemod …

chore(docs): Add changelog for @oceanbase/design@0.2.25, @oceanbase/ui@0.2.26 and @oceanbase/codemod@0.2.8

---

docs/codemod/codemod-CHANGELOG.md

`2023-11-03`
- 🐞 修复 less 函数 `.mixin()` 被错误改写为 `@mixin()` 的问题。[#261](https://github.com/oceanbase/oceanbase-design/pull/261)
- 🐞 修复 `pro-components` 成员没有正确从 `@alipay/ob-ui` 迁移到 `@oceanbase/ui` 的问题。[#262](https://github.com/oceanbase/oceanbase-design/pull/262)

chore(docs): Add changelog for @oceanbase/codemod@0.2.9

---

packages/codemod/transforms/__testfixtures__/less-to-token/obui-less-token-to-token.input.less
packages/codemod/transforms/__testfixtures__/less-to-token/obui-less-token-to-token.output.less
packages/codemod/transforms/__tests__/less-to-token.test.ts
packages/codemod/transforms/less-to-token.js

- None
| 🇺🇸 English | 🐞 Fix not import `~@oceanbase/design/es/theme/index.less` for less file with existed token.         |
| 🇨🇳 Chinese |  🐞 修复包含 token 的 less 文件没有引入 `~@oceanbase/design/es/theme/index.less` 主题文件的问题。        |

fix(codemod): should import ~@oceanbase/design/es/theme/index.less for existed token

---

packages/ui/src/PageContainer/style/index.ts

- None
| 🇺🇸 English | 🐞 Fix PageContainer header style not work.          |
| 🇨🇳 Chinese |  🐞 修复 PageContainer 页头样式未生效的问题。         |

fix(ui): PageContainer header style should cover pro-components

---

packages/design/src/config-provider/index.tsx
packages/design/src/theme/index.ts

- Fix #272.
- ref: https://github.com/ant-design/ant-design/blob/master/components/theme/themes/seed.ts#L32
| 🇺🇸 English |  Not needed         |
| 🇨🇳 Chinese |  Not needed         |

fix(design): seed token should filter colorBgBase, colorTextBase and colorLink to make dark theme work correctly

---

docs/codemod/codemod-CHANGELOG.md
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2023-11-09`
- 🌈 更新中性色板，包括 Design Token 以及 less 主题变量。[#272](https://github.com/oceanbase/oceanbase-design/pull/272)
- 🔥 Drawer [#228](https://github.com/oceanbase/oceanbase-design/pull/228) [@Vanleehao](https://github.com/Vanleehao)
- 🌈 定制主题和样式，符合 OceanBase Design 设计规范。
- 🆕 新增 `footer` 属性，用于设置抽屉的底部内容，默认为 `取消` 和 `确定` 按钮。
- 🆕 新增 `onOk` 和 `onCancel` 属性，用于设置 `取消` 和 `确定` 按钮的回调。
- 🆕 新增 `cancelText` 和 `okText` 属性，用于设置 `取消` 和 `确定` 按钮的文字。
- 🆕 新增 `okButtonProps` 属性，用于设置 `确定` 按钮的属性。
- 🆕 新增 `confirmLoading` 属性，用于设置 `确定` 按钮的加载态。
- 🆕 全局设置 Spin 的加载指示符为 OceanBase 加载动画。[#273](https://github.com/oceanbase/oceanbase-design/pull/273)
- 🆕 Badge、Button、Card、Select、Table、Tag 和 Tooltip 支持转发 `ref`。[#259](https://github.com/oceanbase/oceanbase-design/pull/259) [@linhf123](https://github.com/linhf123)
- 💄 优化 Modal …

chore(docs): Add changelog for @oceanbase/design@0.2.27, @oceanbase/ui@0.2.28 and @oceanbase/codemod@0.2.10

---

.github/workflows/release-helper.yml
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2023-11-14`
- 🌈 新增主题预览和编辑器，便于主题调试和预览。[#287](https://github.com/oceanbase/oceanbase-design/pull/287)
- 💄 优化 Drawer 的标题、内容区和页脚样式，以符合设计规范。[#283](https://github.com/oceanbase/oceanbase-design/pull/283) [@Vanleehao](https://github.com/Vanleehao)
`2023-11-14`
- 🆕 Login 新增 `isMobile`` 属性，用于开启移动端样式。[#288](https://github.com/oceanbase/oceanbase-design/pull/288)
- 🔨 ContentWithQuestion 样式方案从 less 改造为 CSS-in-JS，以支持动态主题。[#283](https://github.com/oceanbase/oceanbase-design/pull/283) [@Vanleehao](https://github.com/Vanleehao)

chore(docs): Add changelog for @oceanbase/design@0.2.28, @oceanbase/ui@0.2.29

---

packages/charts/src/index.ts
packages/ui/src/Action/index.ts
packages/ui/src/BatchOperationBar/index.tsx
packages/ui/src/Dialog/index.tsx
packages/ui/src/DocDialog/index.tsx
packages/ui/src/IconFont/index.tsx
packages/ui/src/NavMenu/index.tsx
packages/ui/src/Ranger/Ranger.tsx
packages/ui/src/TreeSearch/index.tsx
packages/ui/src/index.ts
packages/util/src/index.ts

| 🇺🇸 English | 🤖 Export type definition, including ABasicLayoutProps, BatchOperationBarProps, LoginProps, LottieProps, PasswordProps, RangerProps, RangerProps and TreeSearchProps.          |
| 🇨🇳 Chinese |  🤖 导出 BasicLayoutProps、BatchOperationBarProps、LoginProps、LottieProps、PasswordProps、RangerProps、RangerProps 和 TreeSearchProps 等 TS 类型。         |

feat(ui): Export components' TypeScript definition

---

packages/charts/src/hooks/useTooltipScrollable.ts

图表的 tooltip 配置如果返回一个空对象，仍然会展示tooltip，需要改成 false 才会关闭对应配置
| 🇺🇸 English |     🐞 Fix `tooltip` cannot be closed for Line, Area and DualAxes      |
| 🇨🇳 Chinese |  🐞 修复折线图、面积图和双轴图的 `tooltip` 无法关闭的问题。      |

fix(charts): tooltip cannot be closed for Line, Area and DualAxes

---

packages/design/src/tag/style/index.ts

- None.
| Before (font-size: 14px) | After (font-size: 12px) |
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/729afaaf-4396-4800-8695-d1113d83da9f) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/91854149-f4e9-418b-8775-25a27996a5a8) |
| 🇺🇸 English |   🐞 Fix Tag `font-size` not correct.         |
| 🇨🇳 Chinese |  🐞 修复 Tag 的字体大小不正确的问题。       |

fix(design): Tag font-size not correct

---

docs/charts/charts-CHANGELOG.md
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2023-12-14`
- 🔥 Space 和 Grid 组件的间距样式兼容 Chrome 84 以下的浏览器。[#344](https://github.com/oceanbase/oceanbase-design/pull/344) [@wdyea-ya](https://github.com/wdyea-ya)
- 🌈 更新默认主题的功能色板，包括 Design Token 和 less 变量。[#354](https://github.com/oceanbase/oceanbase-design/pull/354)
- Tag
- 🆕 Tag 新增 `ellipsis` 属性，用于配置内容溢出时的省略和 Tooltip 提示。[#361](https://github.com/oceanbase/oceanbase-design/pull/361)
- 🐞 修复 Tag 字体大小不正确的问题。[#360](https://github.com/oceanbase/oceanbase-design/pull/360)
- 🐞 修复 Select 在多选模式和 `large` & `small` 尺寸下，选中项缺少边框样式的问题。[#332](https://github.com/oceanbase/oceanbase-design/pull/332) [@wdyea-ya](https://github.com/wdyea-ya)
- 💄 优化 Button 样式，包括更新主按钮的渐变色，并去除 `box-shadow` 阴影。[#352](https://github.com/oceanbase/oceanbase-design/pull/352)
- TypeScript
- 🤖 导出 SpaceProps、SpaceSize、ColProps、ColSize …

chore(docs): Add changelog for @oceanbase/design@0.2.32, @oceanbase/ui@0.2.33 and @oceanbase/charts@0.2.19

---

packages/charts/src/Liquid/index.md
packages/charts/src/Liquid/index.tsx

- None
| 🇨🇳 Chinese | 🆕 Liquid 新增 `containerStyle`、`percentStyle` 和 `titleStyle` 属性，分别用于设置容器样式、百分比样式和标题样式。         |

feat(charts): Liquid add containerStyle, percentStyle and titleStyle prop

---

packages/charts/src/Stat/index.tsx

- None.
- 原先根据宽高比 > 2.5 调整图表高度比不太合理，宽高比大并不意味着高度小。根据字体最小为 12px 和迷你图高度最小为 24px，文字和图表重叠的容器高度约为 72px，因此取其作为边界高度。
| 🇺🇸 English |  💄 Stat chart height ratio change from 0.5 to 0.25 when container height < 72         |
| 🇨🇳 Chinese | 💄 Stat 容器高度小于 `72px` 时，图表的高度比例从 `0.5` 减小为 `0.25`。          |

improve(charts): Stat chart height ratio change from 0.5 to 0.25 when container height < 72

---

packages/design/src/config-provider/__tests__/hideOnSinglePage.test.tsx
packages/design/src/config-provider/index.tsx

- Ref: #330
- 统一去掉分页器会有以下问题
- 批量操作场景，批量操作栏位于分页器左侧，此时只有一页数据但也不应该去掉分页器。
- 切换 pageSize 如果达到一页数据，则 pageSize 切换器会被隐藏，无法再切换回去。
| 🇨🇳 Chinese | 🐞 ConfigProvider `hideOnSinglePage` 默认值改为 `false`，交由业务侧按需设置，避免统一去掉分页器带来的问题。          |

fix(design): ConfigProvider hideOnSinglePage change to false by default

---

packages/design/src/table/__tests__/__snapshots__/index.test.tsx.snap
packages/design/src/table/__tests__/index.test.tsx
packages/design/src/table/index.md
packages/design/src/table/index.tsx

- Ref: #330
| 🇨🇳 Chinese |  🐞 修复 Table 只有一页数据且存在批量操作或 `pageSize` 切换时分页器被隐藏的问题。        |

fix(design): Table pagination.hideOnSinglePage should be false when batch operation or pagination.showSizeChanger exist

---

packages/design/src/list/__tests__/__snapshots__/index.test.tsx.snap
packages/design/src/list/__tests__/index.test.tsx
packages/design/src/list/index.md
packages/design/src/list/index.tsx

- Ref: #330
| 🇨🇳 Chinese | 🐞 修复 List 只有一页数据且存在 `pageSize` 切换时分页器被隐藏的问题。          |

fix(design): List pagination.hideOnSinglePage should be false when pagination.showSizeChanger exist

---

docs/charts/charts-CHANGELOG.md
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md
packages/design/src/list/__tests__/__snapshots__/index.test.tsx.snap
packages/design/src/list/__tests__/index.test.tsx

`2023-12-28`
- 🐞 ConfigProvider `hideOnSinglePage` 默认值改为 `false`，避免统一去掉分页器带来的问题。[#388](https://github.com/oceanbase/oceanbase-design/pull/388)
- 🐞 修复 Table 只有一页数据且存在批量操作或 `pageSize` 切换时分页器被隐藏的问题。[#389](https://github.com/oceanbase/oceanbase-design/pull/389)
- 🐞 修复 List 只有一页数据且存在 `pageSize` 切换时分页器被隐藏的问题。[#390](https://github.com/oceanbase/oceanbase-design/pull/390)
- 💄 更新 Design Token，新增 `fontHeight`、`fontHeightLG` 和 `fontHeightSM` less 变量。[#381](https://github.com/oceanbase/oceanbase-design/pull/381)
---
`2023-12-28`
- IconFont
- 🐞 修复 IconFont 会请求不必要 JS 资源的问题。[#375](https://github.com/oceanbase/oceanbase-design/pull/375)
- 📢 将 IconFont 组件标记为即将废弃，不推荐使用。[#375](https://github.com/oceanbase/oceanbase-design/pull/375)
- 💄 优化 TagSelect 的 `disabled` 和 `hover` 样式，并将固定样式改造为 Design …

chore(docs): Add changelog for @oceanbase/design@0.2.33, @oceanbase/ui@0.2.34 and @oceanbase/charts@0.2.20

---

docs/charts/charts-CHANGELOG.md
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2024-01-18`
- 🆕 ConfigProvider 新增 table.selectionColumnWidth 属性，用于配置表格的展开列宽度。[#421](https://github.com/oceanbase/oceanbase-design/pull/421)
- 🐞 修复 Table 可展开时底部出现重复边框的问题。[#420](https://github.com/oceanbase/oceanbase-design/pull/420)
- Table
- 💄 优化 Table 在无间距卡片内的展示样式，包括第一列和卡片标题对齐、最后一列和卡片操作区对齐、分页器左右增加间距。[#422](https://github.com/oceanbase/oceanbase-design/pull/422)
- 💄 减小 Table 单元格的纵向内间距，以对齐设计规范。[#425](https://github.com/oceanbase/oceanbase-design/pull/425)
- 💄 Modal 去掉最大高度限制，高度超出时内容滚动改由上层控制。[#411](https://github.com/oceanbase/oceanbase-design/pull/411)
---
`2024-01-18`
- 🐞 修复 Password 组件快速输入时丢失字符和焦点跳跃的问题。[#424](https://github.com/oceanbase/oceanbase-design/pull/424) [@Vanleehao](https://github.com/Vanleehao)
- 🐞 修复 Highlight 国际化不生效的问题。[#419](https://github.com/oceanbase/oceanbase-design/pul …

chore(docs): Add changelog for @oceanbase/design@0.2.35, @oceanbase/ui@0.2.36 and @oceanbase/charts@0.2.22

---

docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2024-01-19`
- 💄 ConfigProvider 内嵌的 App 组件不再创建 DOM 节点，避免增加一层 DOM 结构影响子元素的样式表现。[#431](https://github.com/oceanbase/oceanbase-design/pull/431)
---
`2024-01-19`
- PageContainer
- 💄 PageContainer 页头和页脚操作区的组件尺寸默认为 `large`、字体大小为 `middle`。[#432](https://github.com/oceanbase/oceanbase-design/pull/432)
- 💄 优化 PageContainer 和 Tabs 组合使用时的间距，以对齐设计规范。[#434](https://github.com/oceanbase/oceanbase-design/pull/434)
- 💄 FooterToolbar 子元素的组件尺寸默认为 `large`、字体大小默认为 `middle`。[#433](https://github.com/oceanbase/oceanbase-design/pull/433)

chore(docs): Add changelog for @oceanbase/design@0.2.36, @oceanbase/ui@0.2.37

---

packages/ui/src/FooterToolbar/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/FooterToolbar/index.tsx
packages/ui/src/PageContainer/index.tsx

- Fix #433.
- Ref: #443.
- 原先基于 ConfigProvider 修改组件尺寸的影响范围不可控，需要改为原来的样式定制方案，并优化样式以适配更多组件场景。
| 🇨🇳 Chinese | 🐞 修复 FooterToolbar 子元素外的组件尺寸也可能被改为 `large` 的问题。           |

fix(ui): FooterToolbar children large size should work correctly

---

docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2024-01-30`
- 🆕 新增 injectStaticFunction 属性，用于配置 message、notification 和 Modal 静态方法是否可以消费全局配置，默认开启。[#446](https://github.com/oceanbase/oceanbase-design/pull/446)
- 🐞 修复 Typography 的样式优先级，保证字体和行高默认继承父元素，便于和其他组件组合使用。[#428](https://github.com/oceanbase/oceanbase-design/pull/428) [@wdyea-ya](https://github.com/wdyea-ya)
- 🐞 修复 Table 选中行和 `hover` 行的背景色不一致的问题。[#455](https://github.com/oceanbase/oceanbase-design/pull/455)
---
`2024-01-30`
- PageContainer
- 🐞 修复 PageContainer 页头和页脚操作区外的组件尺寸也可能被改为 large 的问题。[#443](https://github.com/oceanbase/oceanbase-design/pull/443)
- 💄 修复 PageContainer 页头和页脚操作区样式适配 Space.Compact 组件。[#454](https://github.com/oceanbase/oceanbase-design/pull/454)
- 🐞 修复 FooterToolbar 子元素外的组件尺寸被改为 large 的问题。[#447](https://github.com/oceanbase/oceanbase-design/pull/447)

chore(docs): Add changelog for @oceanbase/design@0.2.37 and @oceanbase/ui@0.2.38

---

packages/design/src/_util/genComponentStyleHook.ts

- None.
| 🇨🇳 Chinese | 💄 组件的样式加载顺序调整为 `-900`，保证自定义样式的优先级高于 antd。          |

[Feature Branch] improve(design): style order should behind of antd to cover it

---

packages/codemod/transforms/utils/token.js

- None.
- None.
| 🇨🇳 Chinese | 🆕 新增颜色值 `rgb(250,250,250)` 到 `colorBgLayout` 的自动改写。         |

[Feature Branch] improve(codemod): rgb(250,250,250) => colorBgLayout for style-to-token and less-to-token

---

docs/codemod/codemod-CHANGELOG.md
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2024-03-22`
- ⭐️ 去掉所有组件的重置样式，避免被 Tooltip、Popover、Space、Dropdown 等组件包裹时字体大小、颜色被覆盖。[#450](https://github.com/oceanbase/oceanbase-design/pull/450)
- ⭐️ 组件的样式加载顺序改为 -900，保证自定义样式的优先级高于 antd。[#464](https://github.com/oceanbase/oceanbase-design/pull/464)
- 🌈 更新中性色板，包括 Design Token 以及 less 主题变量。[#484](https://github.com/oceanbase/oceanbase-design/pull/484)
- 🔥 新版 Empty 组件 [#465](https://github.com/oceanbase/oceanbase-design/pull/465)
- 💄 定制插图、主题和样式，以符合 OceanBase Design 设计规范。
- 🆕 新增 `title` 属性，用于设置空状态标题。
- 🆕 新增 `steps` 属性，用于设置步骤引导。
- 🆕 新增 `layout` 属性，用于设置空状态布局，默认为 vertical。
- 🆕 通过 ConfigProvider `renderEmpty` 定制全局组件的空状态。[#467](https://github.com/oceanbase/oceanbase-design/pull/467)
- 🔥 新版 Result 组件 [#476](https://github.com/oceanbase/oceanbase-design/pull/476)
- 💄 定制插图、主题和样式，以符合 OceanBase Design …

[Feature Branch] chore(docs): Add changelog for @oceanbase/design@0.3.0, @oceanbase/ui@0.3.0 and @oceanbase/codemod@0.3.0

---

packages/design/src/modal/Modal.tsx
packages/design/src/modal/__tests__/__snapshots__/modal.test.tsx.snap
packages/design/src/modal/__tests__/modal.test.tsx

- Fix #522
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/0a923091-2ce9-4ec5-a471-2d703769e020) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/928f7445-2073-4197-8d5e-309abc675cc0) |
| 🇨🇳 Chinese | 🐞 修复 Modal `footer` 为 `false` 时页脚 DOM 未去掉的问题。         |

fix(design): Modal should hide footer dom when footer is false

---

packages/design/src/config-provider/__tests__/__snapshots__/form.test.tsx.snap
packages/design/src/config-provider/__tests__/form.test.tsx
packages/design/src/config-provider/index.tsx
packages/design/src/form/demo/pro-form.tsx
packages/design/src/form/index.md

- None
| 🇨🇳 Chinese | 🐞 ConfigProvider `form.requiredMark` 属性的默认值改为 `optional`，保证 ProForm 等 Form 衍生组件也能生效。         |

fix(design): ConfigProvider form.requiredMark should be `optional` by default and work for ProForm

---

.dumi/theme/SiteThemeProvider.tsx
.dumi/theme/common/ThemeSwitch/index.tsx
.dumi/theme/layouts/GlobalLayout.tsx
.dumi/theme/locales/en-US.json
.dumi/theme/locales/zh-CN.json
packages/design/src/_util/genComponentStyleHook.ts
packages/design/src/config-provider/__tests__/theme.test.tsx
packages/design/src/config-provider/index.md
packages/design/src/config-provider/index.tsx
packages/design/src/index.ts

- None
| 🇨🇳 Chinese | 🆕 新增 `theme.customFont` 属性，用于开启 `Source Sans Pro` 定制字体以提升展示效果，仅支持线上应用和英文环境。          |

feat(design): ConfigProvider add theme.customFont prop to use `Source Sans Pro` font

---

packages/design/src/input/__tests__/__snapshots__/placeholder.test.tsx.snap
packages/design/src/input/__tests__/placeholder.test.tsx
packages/design/src/locale/index.ts
packages/design/src/select/__tests__/__snapshots__/placeholder.test.tsx.snap
packages/design/src/select/__tests__/placeholder.test.tsx
packages/design/src/select/demo/basic.tsx
packages/design/src/select/index.md
packages/design/src/select/index.tsx

- None
| 🇨🇳 Chinese | - 📢 Select 默认填充 `placeholder`，并支持通过 ConfigProvider `locale.global.placeholder` 或 `locale.Select.placeholder` 进行全局配置。- 🆕 ConfigProvider 新增 `locale.Select.placeholder` 属性，用于配置 Select 的默认 `placeholder`。          |

feat(design): Select add default placeholder and ConfigProvider support to config it global

---

packages/design/src/config-provider/__tests__/static-function.test.tsx
packages/design/src/static-function/index.tsx
packages/design/src/theme/style/compact.less
packages/design/src/theme/style/default.less
plugin-theme-less.ts

- None
- None
| 🇨🇳 Chinese | 🐞 修复主题 Token `boxShadow` 和 `boxShadowSecondary`  通过静态 token 对象和 less 变量访问时值不正确的问题。        |

fix(design): boxShadow and boxShadowSecondary for static token and less token should be correct

---

.dumirc.ts
packages/ui/package.json
packages/ui/src/LightFilter/demo/basic.tsx
packages/ui/src/LightFilter/index.md
packages/ui/src/LightFilter/index.tsx
packages/ui/src/LightFilter/style/index.ts
packages/ui/src/index.ts
pnpm-lock.yaml

- None
- Design Guide:
| Middle | Small |
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/d3c915b2-c58a-4da3-9555-6cc85f029f1c) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/c57c9286-3e73-4762-85aa-2136c17f15eb) |
| 🇨🇳 Chinese | 💄 优化 LightFilter 圆角、内间距、背景色等样式，以对齐设计规范。         |

💄 improve(ui): LightFilter style

---

.dumirc.ts
packages/charts/src/Area/demo/basic.tsx
packages/charts/src/Area/demo/stack.tsx
packages/charts/src/Area/demo/tooltip-scrollable.tsx
packages/charts/src/Area/index.tsx
packages/charts/src/Column/index.tsx
packages/charts/src/DualAxes/index.tsx
packages/charts/src/Line/demo/basic.tsx
packages/charts/src/Line/index.tsx

- None
| 🇨🇳 Chinese | 🐞 Line、Area、Column 和 DualAxes 去掉不合理的 `xAxis.tickCount` 计算逻辑，改由上层进行控制。         |

🐞 fix(charts): Remove unreasonable xAxis.tickCount calculate logic for Line, Area, Column and DualAxes

---

packages/design/src/config-provider/__tests__/static-function.test.tsx
packages/design/src/static-function/index.tsx
packages/design/src/theme/style/compact.less
packages/design/src/theme/style/default.less
plugin-theme-less.ts

- Fix #552
- None
| 🇨🇳 Chinese | 🐞 修复主题 Token `boxShadowSecondary` 通过静态 token 对象和 less 变量访问时值不正确的问题         |

fix(design): boxShadowSecondary for static token and less token should be correct

---

packages/ui/src/Boundary/Components/Code.tsx
packages/ui/src/Boundary/Components/Exception.tsx
packages/ui/src/Boundary/Components/Function.tsx

- None
- None
| 🇨🇳 Chinese | 🆕 Boundary 组件支持 `className` 属性，并且根据不同组件内置 `ob-boundary-error`、`ob-boundary-403` 和 `ob-boundary-404` 类名，便于上层判断异常类型。         |

feat(ui): Boundary add className prop + built in ob-boundary-error, ob-boundary-403 and ob-boundary-404 className

---

packages/design/src/config-provider/__tests__/theme.test.tsx
packages/design/src/config-provider/index.tsx

- None
- None
| 🇨🇳 Chinese | 🐞 修复 ConfigProvider 开启 `theme.customFont` 并且多次嵌套后 `fontFamily` 不正确的问题。         |

fix(design): fontFamily in nested ConfigProvider should be correct when enable theme.customFont

---

packages/design/src/config-provider/__tests__/injectStaticFunction.test.tsx
packages/design/src/config-provider/index.tsx
packages/design/src/static-function/index.tsx

- Improve #446
- None
| 🇨🇳 Chinese | 🐞 修复 ConfigProvider 多次使用会默认多次注入 StaticFunction，导致 Modal、message 和 notification 静态方法不会正常展示的问题。          |

fix(design): ConfigProvider should not inject StaticFunction many times by default

---

docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2024-04-25`
- ConfigProvider
- 🐞 修复 ConfigProvider 开启 `theme.customFont` 并且多次嵌套后 `fontFamily` 不正确的问题。[#572](https://github.com/oceanbase/oceanbase-design/pull/572)
- 🐞 修复 ConfigProvider 自定义 `theme.token.fontFamily` 不生效的问题。[#573](https://github.com/oceanbase/oceanbase-design/pull/573)
- 🐞 修复 ConfigProvider 多次使用会默认多次注入 StaticFunction，导致 Modal、message 和 notification 静态方法不会正常展示的问题。[#574](https://github.com/oceanbase/oceanbase-design/pull/574)
- 🐞 修复主题 Token `boxShadowSecondary` 通过静态 token 对象和 less 变量访问时值不正确的问题。[#569](https://github.com/oceanbase/oceanbase-design/pull/569)
- 💄 优化 Radio.Button 选中置灰态的背景颜色，避免和字体颜色区分不清。[#570](https://github.com/oceanbase/oceanbase-design/pull/570)
---
`2024-04-25`
- ⭐️ Boundary 组件支持 `className` 属性，并且根据不同组件内置 ob-boundary-error、ob-boundary-403 和 ob-boundary-404 …

chore(docs): Add changelog for @oceanbase/design@0.3.3 and @oceanbase/ui@0.3.3

---

packages/ui/src/PageContainer/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/PageContainer/demo/basic.tsx
packages/ui/src/PageContainer/demo/complete.tsx
packages/ui/src/PageContainer/demo/empty.tsx
packages/ui/src/PageContainer/demo/extra-footer.tsx
packages/ui/src/PageContainer/demo/with-tabs.tsx
packages/ui/src/PageContainer/index.md
packages/ui/src/PageContainer/index.tsx
packages/ui/src/PageContainer/style/index.ts

- None
- Design guide:
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/411fcec3-26b2-494e-a1c3-14454741d6d4) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/42952fa9-8a4b-433c-bead-9a7e8ba75ef7) |
| 🇨🇳 Chinese | 💄 调整 PageContainer 刷新图标的大小和间距，以对齐设计规范。          |

improve(ui): PageContainer style

---

packages/design/src/table/__tests__/index.test.tsx
packages/design/src/table/demo/row-selection.tsx
packages/design/src/table/index.tsx

1. BatchOperationBar less locale
2. BatchOperationBar don't related rowSelection
3. API Unrealized
| ![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/2e175231-931f-46dc-97ce-778f8583ad3f)| ![image](https://github.com/oceanbase/oceanbase-design/assets/32009993/41ad0186-c640-4212-aae7-085b568cc4cb)|
| 🇺🇸 English |  Fix batchOperationBar don't related rowSelection and locale   |
| 🇨🇳 Chinese |    修复批量操作栏未关联 rowSelection ，以及缺少国际化 |

fix(design): Table locale & BatchOperationBar keys should related rowSelection 

---

packages/design/src/config-provider/__tests__/theme.test.tsx
packages/design/src/config-provider/index.tsx

fix(design): ConfigProvider theme.isAliyun should work correctly

---

packages/design/src/_util/genStyle.ts
packages/design/src/config-provider/demo/size.tsx
packages/design/src/empty/demo/complete-debug.tsx
packages/design/src/empty/style/index.ts
packages/design/src/index.ts
packages/ui/src/FooterToolbar/style/index.ts
packages/ui/src/PageContainer/style/index.ts

| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/6bce83c7-3659-49eb-a912-ba7be7b21957) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/fb8c3fca-e1cd-4aa0-8325-757db1b99b6d) |
| 🇨🇳 Chinese | 💄 优化 Empty 操作区的按钮样式，加大行高和圆角。          |

improve(design): Empty footer style

---

packages/design/src/card/index.tsx

- None
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/1077786c-e7fe-4fa8-aeca-71c1b6024fb4) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/cbec72db-89a0-4f00-993a-c1192044abe6) |
| 🇨🇳 Chinese | 💄 优化 Table 在无间距卡片内的展示样式，包括第一列和卡片标题对齐、最后一列和卡片操作区对齐、分页器左右增加间距。          |

improve(design): Table padding when Card styles.body.padding is 0

---

packages/design/src/theme/default.ts
packages/design/src/theme/style/compact.less
packages/design/src/theme/style/default.less

- None
- `#132039` => `#000000` for `colorBgBase`.
| 🇨🇳 Chinese | - 💄 更新 Design Token `colorBgBase` 的颜色值 `#132039` => `#000000`。          |

improve(design): Update colorBgBase token

---

packages/design/src/button/demo/dropdown.tsx
packages/design/src/button/demo/icon.tsx
packages/design/src/button/index.md

- None
| Icon Button | Dropdown Button |
| ![image](https://github.com/user-attachments/assets/0d5c6d7c-c289-4007-973f-8a066c4106ca) | ![image](https://github.com/user-attachments/assets/a5f0dcc2-d42c-4271-a0e1-aeaa684fda26) |

chore(design): Add icon and dropdown button demo

---

docs/codemod/codemod-CHANGELOG.md
docs/design/design-CHANGELOG.md

`2024-07-26`
- 📖 补充 Button、Input 和 Switch 的示例和文档。[#640](https://github.com/oceanbase/oceanbase-design/pull/640) [#657](https://github.com/oceanbase/oceanbase-design/pull/657) [#658](https://github.com/oceanbase/oceanbase-design/pull/658)
- 📖 新增阿里云和 less 主题使用文档，优化暗色主题使用文档。[#644](https://github.com/oceanbase/oceanbase-design/pull/644)
- ⭐️ 新增阿里云主题的 less 变量文件，方便在 less 中使用。[#643](https://github.com/oceanbase/oceanbase-design/pull/643)
- 💄 更新 Design Token `colorBgBase` 的颜色值 `#132039` => `#000000`。[#642](https://github.com/oceanbase/oceanbase-design/pull/642)
- 💄 优化 Table 表头的字体颜色，以对齐设计规范。[#641](https://github.com/oceanbase/oceanbase-design/pull/641)
---
`2024-07-26`
- ⭐️ 新增 `rgba(0,0,0,xx%)` 颜色值到 Design Token 的自动改写。[#656](https://github.com/oceanbase/oceanbase-design/pull/656)
- ⭐️ 支持 …

chore(docs): Add changelog for @oceanbase/design@0.3.7 and @oceanbase/codemod@0.3.6

---

packages/design/src/_util/useFlexGapSupport.ts

- None
| 🇨🇳 Chinese | - 🐞 修复 Space 在新版浏览器下可能出现的间距抖动问题。          |

fix(design): Space should be flexible by default to avoid shrink

---

.dumi/theme/common/ThemeSwitch/index.tsx
.dumi/theme/layouts/GlobalLayout.tsx
.dumirc.ts
docs/spec/typography.md
packages/design/src/_util/genComponentStyleHook.ts
packages/design/src/config-provider/__tests__/theme.test.tsx
packages/design/src/config-provider/index.md
packages/design/src/config-provider/index.tsx
packages/design/src/theme/default.ts
packages/design/src/theme/style/aliyun.less
packages/design/src/theme/style/compact.less
packages/design/src/theme/style/dark.less
packages/design/src/theme/style/default.less
packages/design/src/theme/util/format.ts

- 字体规范: https://design.oceanbase.com/docs/spec/typography#%E5%AD%97%E4%BD%93%E6%A0%B7%E5%BC%8F
- None
| 🇨🇳 Chinese | - ⭐️ 更新默认字体、英文字体和代码字体，并且会根据语言设置自动切换默认字体和英文字体。          |

[Feature Branch] improve(design): Update fontFamily, fontFamilyCode and fontFamilyEn

---

packages/ui/src/DateRanger/PickerPanel.tsx
packages/ui/src/DateRanger/Ranger.tsx
packages/ui/src/DateRanger/__test__/index.test.tsx
packages/ui/src/DateRanger/index.less

| <img width="543" alt="image" src="https://github.com/user-attachments/assets/8ce355d6-928b-4242-8a29-af30760d38d9"> | <img width="532" alt="image" src="https://github.com/user-attachments/assets/6077d783-7b0e-493a-9413-09335ca731d4"> |
| 🇺🇸 English | 1. Adjust layout for DateRanger 2. Date/Time Input support quick selected 3. fixed rc-picker was not updated when manually set date          |
| 🇨🇳 Chinese |  1. 调整DateRanger布局 2. 日期和时间输入框支持快捷选中 3. 修复手动输入日期时日历面板不更新的问题         |

feat(ui): [date-ranger] use new layout for picker and support auto selection

---

packages/ui/src/Ranger/QuickPicker.tsx
packages/ui/src/Ranger/Ranger.tsx
packages/ui/src/Ranger/index.md

When I needed to set attributes for Antd'Dropdown, I found that it was not possible to pass it through to QuickPicker, so I supplemented the attribute pass-through.
| 🇺🇸 English |   support rest props for quick picker        |
| 🇨🇳 Chinese |  Ranger组件支持透传props到QuickPicker         |

feat(ui): [ranger] support rest props for quick picker

---

packages/ui/src/DateRanger/PickerPanel.tsx
packages/ui/src/DateRanger/Ranger.tsx
packages/ui/src/DateRanger/__test__/index.test.tsx
packages/ui/src/DateRanger/constant/index.ts
packages/ui/src/DateRanger/index.md

| ![image](https://github.com/user-attachments/assets/5d5869fb-1f33-494d-93b8-7c4821c09fff) | ![image](https://github.com/user-attachments/assets/24796ad4-7d8b-4265-b62f-90c64fb1e0ea) |
| 🇨🇳 Chinese |  1. 默认关闭极简模式 <br/>2. 默认展示年份 <br/>3. 默认展示秒 <br/>4. 使用刷新icon替换当前按钮 <br/>5. 移除快捷选项的tag <br/>6. 调整布局样式 <br/>7. tip和err msg 移到面板底部 <br/>8. 更新测试用例 <br/>9. 自定义时间默认不自动计算时间跨度 & 移除自定义选项        |

feat(ui): [date-ranger] improve func and add more props

---

packages/design/src/theme/default.ts

| ![image](https://github.com/user-attachments/assets/28a6caaf-fd93-466c-b80b-3db0507588ca) | ![image](https://github.com/user-attachments/assets/dbcf589f-5f07-4a21-9812-bacec727ec5c) |
| 🇨🇳 Chinese |  - 💄 将 Breadcrumb 最后一项的字体颜色改为 `#5c6b8a`。         |

improve(design): Breadcrumb last item color

---

packages/design/src/config-provider/__tests__/__snapshots__/appProps.test.tsx.snap
packages/design/src/config-provider/__tests__/appProps.test.tsx
packages/design/src/config-provider/index.md
packages/design/src/config-provider/index.tsx

| 🇨🇳 Chinese | - ⭐️ ConfigProvider 新增 `appProps` 属性，用于控制内嵌 App 是否渲染组件、以便让被包裹元素继承 `.ant-app` 样式。        |

improve(design): ConfigProvider add appProps to control .ant-app style work

---

packages/design/src/index.ts
packages/design/src/radio/index.tsx
packages/design/src/switch/demo/text.tsx
packages/design/src/switch/index.md
packages/design/src/switch/index.ts
packages/design/src/switch/index.tsx
packages/design/src/switch/style/index.ts

| ![image](https://github.com/user-attachments/assets/93d47059-92ad-423a-ae85-521ba8107145) | ![image](https://github.com/user-attachments/assets/42fe898e-0da7-42c3-9c67-09354b6abc76) |
| 🇨🇳 Chinese | - 💄 优化 Switch 未选中态的背景色，和置灰态的背景色进行区分。          |

improve(design): Switch unchecked background color

---

packages/ui/src/DateRanger/index.less

Use prefixCls instead of fixed class names.
| 🇺🇸 English | use prefixCls var  instead of fixed class names        |
| 🇨🇳 Chinese | 使用less变量替换写死的类名          |

chore(ui): use prefixCls less var for DateRanger

---

packages/design/src/typography/Link.tsx
packages/design/src/typography/Paragraph.tsx
packages/design/src/typography/Text.tsx
packages/design/src/typography/Title.tsx
packages/design/src/typography/demo/editable.tsx
packages/design/src/typography/hooks/useClassName.ts
packages/design/src/typography/index.md
packages/design/src/typography/style/index.ts

- None
| ![2024-11-19 15-48-52 2024-11-19 15_49_54](https://github.com/user-attachments/assets/fbb15716-fb35-4408-a66c-7d4e15c6e97e) | ![2024-11-19 15-41-56 2024-11-19 15_44_52](https://github.com/user-attachments/assets/df828c80-fc90-4cdb-98f9-2601d38a36d2) |
| 🇨🇳 Chinese | - 💄 Typography 编辑模式文本触发器增加 hover 边框，以提示用户可以点击进行编辑。- 💄 优化 Typography 编辑模式样式，避免只读态和编辑态之间切换时出现抖动。          |

improve(design): Typography editable and editing style

---

packages/design/src/empty/demo/over-length.tsx
packages/design/src/empty/index.md
packages/design/src/empty/style/index.ts

| ![image](https://github.com/user-attachments/assets/0aa5da4a-e117-4f41-b20f-6c31fc73c6f7) | ![image](https://github.com/user-attachments/assets/9720051f-c5c9-48ea-9daf-4709d8a1dbf2) |
| 🇨🇳 Chinese | - 💄 优化 Empty 超长内容的样式，限制描述区的最大宽度为 600px、步骤区的最大宽度为 1000px。          |

improve(style): Empty description max-width => 600px and steps max-width => 1000px for over length style

---

packages/design/src/tooltip/MouseTooltip.tsx
packages/design/src/tooltip/__tests__/index.test.tsx
packages/design/src/tooltip/demo/mouse-follow.tsx
packages/design/src/tooltip/index.tsx

- None
| 🇨🇳 Chinese | - 🐞 修复 Tooltip 开启 `mouseFollow` 后没有继承 `.ant-tooltip` 类名和样式的问题。          |

fix(design): mouseFollow Tooltip should inherit `.ant-tooltip` className

---

.dumirc.ts
packages/design/src/popconfirm/demo/basic.tsx
packages/design/src/popconfirm/demo/promise.tsx
packages/design/src/popconfirm/index.md

- None
| 🇨🇳 Chinese | - 📖 新增 Popconfirm 的文档和示例。          |

feat(design): Add Popconfirm docs and demos

---

.dumirc.ts
packages/design/src/date-picker/demo/basic.tsx
packages/design/src/date-picker/demo/ranger-picker.tsx
packages/design/src/date-picker/index.md

- None
| 🇨🇳 Chinese | - 📖 新增 DatePicker 的文档和示例。          |

feat(design): Add DatePicker docs and demos

---

packages/design/src/date-picker/demo/basic.tsx
packages/design/src/date-picker/demo/format.tsx
packages/design/src/date-picker/demo/global-format.tsx
packages/design/src/date-picker/index.md
packages/ui/src/locale/en-US.ts

- None
| 🇨🇳 Chinese | - 📖 DatePicker 新增全局设置日期格式的示例。          |

feat(design): DatePicker add format and global format demo

---

docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2024-11-29`
- 📖 新增 DatePicker 的文档和示例。[#852](https://github.com/oceanbase/oceanbase-design/pull/852)
- 📖 新增 TimePicker 的文档和示例。[#853](https://github.com/oceanbase/oceanbase-design/pull/853)
- 📖 新增 Popconfirm 的文档和示例。[#851](https://github.com/oceanbase/oceanbase-design/pull/851)
- 📖 新增 Popover 的文档和示例。[#850](https://github.com/oceanbase/oceanbase-design/pull/850)
- 📖 新增 Progress 的文档和示例。[#834](https://github.com/oceanbase/oceanbase-design/pull/834)
- 🌈 将 Design Token lineWidthFocus 设为 0，以去掉组件聚焦时的线条样式。[#841](https://github.com/oceanbase/oceanbase-design/pull/841)
- ⭐️ 优先从系统加载 `Inter`、`Consolas` 和 `Helvetica Neue` 字体。[#861](https://github.com/oceanbase/oceanbase-design/pull/861)
- 🐞 修复 Slider 两端标签的对齐样式在部分场景下不生效的问题。[#832](https://github.com/oceanbase/oceanbase-design/pull/832)
- 💄 将全局的滚动条颜色改为 …

chore(docs): Add changelog for @oceanbase/design@0.4.2 and @oceanbase/ui@0.4.2

---

packages/ui/src/locale/en-US.ts

- Fix #854
| 🇨🇳 Chinese | - 🐞 修复引入的 @oceanbase/design 国际化语言路径不正确、导致运行报错的问题。          |

fix(ui): @oceanbase/design locale file should import correctly

---

packages/ui/src/TaskGraph/Graph.tsx

- None
| 🇨🇳 Chinese | - ⚡ TaskGraph 依赖的 `@antv/g6` 改为动态加载，以提升加载性能。          |

optimize(ui): dynamic import @antv/g6 for load perf

---

packages/ui/src/Action/Item.tsx
packages/ui/src/Action/index.md

Sometimes we need like `event.stopPropagation` to customize event behavior.
| 🇺🇸 English | - 🆕 The click event of the Action component supports the e param。 |
| 🇨🇳 Chinese | - 🆕 Action 组件 onClick 函数增加 event 参数。  |

feat(ui): Action onClick add event param

---

packages/design/src/table/style/index.ts

- None
| [Image] | [Image] |
| 🇨🇳 Chinese | - 💄 优化 Table 空状态在 Popover、Tooltip 下的高度。         |

improve(design): Table empty height in Popover and Tooltip

---

packages/design/src/global.css

- 之前为了解决 CodeSandbox 不支持 `~` 解析的问题，去掉了 `~` 路径。但在 Umi 3 & Bigfish 3 下路径解析有问题，需要改回去。
```diff
-@import 'antd/dist/reset.css';
+@import '~antd/dist/reset.css';
```
- Ref: #855
| 🇨🇳 Chinese | - 🔨 修改 antd 重置样式的引入路径 `antd/dist/reset.css` => `~antd/dist/reset.css`，以适配 Umi 3 & Bigfish 3 的解析逻辑。         |

improve(design): path resolve compatible with bigfish 3

---

docs/design/design-CHANGELOG.md

`2024-12-16`
- 🐞 修复 antd 重置样式的引入路径 `antd/dist/reset.css` => `~antd/dist/reset.css`，以适配 Umi 3 和 Bigfish 3 的解析逻辑。[#894](https://github.com/oceanbase/oceanbase-design/pull/894)

chore(docs): Add changelog for @oceanbase/design@0.4.4

---

packages/ui/src/Action/demo/with-tooltip-popconfirm.tsx
packages/ui/src/Action/index.md

- None
| 🇨🇳 Chinese | - 📖 Action 新增带 Tooltip 和 Popconfirm 的示例。         |

chore(ui): Add Action demo with tooltip and popconfirm

---

packages/ui/src/Action/Group.tsx
packages/ui/src/Action/index.md

- Improve Action `moreType` auto judge logic:
| ![image](https://github.com/user-attachments/assets/175deff7-be60-451e-9dd5-c5e0282b6ada) | ![image](https://github.com/user-attachments/assets/50b58d99-43fc-45ad-8b2c-066b59ff5256) |
| 🇨🇳 Chinese | - 💄 优化 Action 更多操作元素类型的判断逻辑。- 🆕 Action 新增 `moreType` 属性，用于设置更多操作的元素类型。          |

feat(ui): Action add moreType prop and improve its judge logic

---

.dumi/theme/common/styles/Markdown.tsx
packages/design/src/table/demo/expandable.tsx
packages/design/src/table/demo/multiple-nesting-tables.tsx
packages/design/src/table/demo/nesting-tables.tsx
packages/design/src/table/index.md
packages/design/src/table/index.tsx
packages/design/src/table/style/index.ts

- None
| 🇨🇳 Chinese | - 💄 Table 点击行可展开时，设置行样式为 `cursor: pointer`。         |

improve(design): Add cursor style for expandRowByClick Table

---

packages/ui/src/DateRanger/PickerPanel.tsx
packages/ui/src/DateRanger/Ranger.tsx
packages/ui/src/DateRanger/demo/basic.tsx
packages/ui/src/DateRanger/demo/locale.tsx
packages/ui/src/DateRanger/index.less

close #919
| ![image](https://github.com/user-attachments/assets/ab82764b-59d7-4218-b381-000882574255)| ![image](https://github.com/user-attachments/assets/92d28dc7-3547-4e62-9b08-368186287938)![image](https://github.com/user-attachments/assets/28caf557-3593-466c-9cbe-48de56463153)|
| 🇺🇸 English | -  support clear        |
| 🇨🇳 Chinese | - 🐞 修复 DateRanger `allowClear` 不生效的问题。   |

fix(ui): DateRanger allowClear should work 

---

packages/design/src/card/demo/border-less.tsx
packages/design/src/card/demo/no-divider.tsx
packages/design/src/space/demo/vertical.tsx
packages/design/src/table/demo/card-table.tsx
packages/design/src/table/demo/pro-card-table.tsx
packages/ui/src/ProCard/demo/basic.tsx
packages/ui/src/ProCard/style/index.ts

- None
| ![image](https://github.com/user-attachments/assets/4652c6ba-a748-468a-b8b6-1678fb8bf88b) | ![image](https://github.com/user-attachments/assets/89d64cb7-9f28-4825-8334-27ff8563538f) |
| ![image](https://github.com/user-attachments/assets/e2ec3116-07a8-4259-a5a9-4235709dfbee) | ![image](https://github.com/user-attachments/assets/e2792825-da20-4352-a335-ffa03963d7cf) |
| 🇨🇳 Chinese | - 💄 优化 ProCard 的圆角、阴影、内间距，以对齐 Card 样式。          |

improve(ui): ProCard border-radius, box-shadow and body padding follow Card style

---

packages/ui/src/DateRanger/PickerPanel.tsx
packages/ui/src/DateRanger/Ranger.tsx
packages/ui/src/DateRanger/demo/rules.tsx
packages/ui/src/DateRanger/index.md
packages/ui/src/DateRanger/index.ts

| - | ![image](https://github.com/user-attachments/assets/8b925f9a-9679-4a00-a94f-a10d426f6458)  |
| - | ![image](https://github.com/user-attachments/assets/f579e840-3471-4bb0-8692-952d880c4d10) |
| 🇺🇸 English |   -      |
| 🇨🇳 Chinese |   - 🆕 DateRanger 新增 `rules` 属性，用于设置起止时间的校验规则。        |

feat(DateRanger): Open rules verification function

---

packages/design/src/table/style/index.ts

- None
| size | Before | After |
| :--- | :--- | :--- |
| large | ![image](https://github.com/user-attachments/assets/43d8d653-3082-4191-a4a7-eb8e33d23840) | ![image](https://github.com/user-attachments/assets/573faa82-7f70-44d9-9263-5c5b4bfe4871) |
| middle  | ![image](https://github.com/user-attachments/assets/219d6ded-3729-4389-83d9-500b040a053f) | ![image](https://github.com/user-attachments/assets/aa85b252-dc2e-4f41-9803-17feaf7c9d91) |
| small | ![image](https://github.com/user-attachments/assets/8dc5f133-a4ec-43a0-b258-70d8b4d229df) | ![image](https://github.com/user-attachments/assets/751a0381-324e-4876-bd40-f23ae6d88197) |
| 🇨🇳 Chinese | - 💄 优化 Table 空状态的高度，大中小尺寸分别为 360px、260px 和 160px。      |
⚠️ …

improve(design): middle and small Table empty height

---

packages/design/src/form/FormItem.tsx
packages/design/src/form/__tests__/__snapshots__/switch.test.tsx.snap
packages/design/src/form/__tests__/switch.test.tsx

- None
| ![image](https://github.com/user-attachments/assets/e677cc57-a905-4df9-893b-f592cb419f20) | ![image](https://github.com/user-attachments/assets/f8227db8-e3af-44ea-923f-a52a44eb6ce2) |
| 🇨🇳 Chinese | - 💄 默认去掉 Form.Item 包裹 Switch 时的可选样式。         |

improve(design): Set required to true for Form.Item with Switch to hide optional mark

---

packages/design/src/card/demo/with-form.tsx
packages/design/src/card/index.md
packages/design/src/modal/demo/form.tsx
packages/design/src/modal/index.md

- None
| Modal form | Card form |
| ![image](https://github.com/user-attachments/assets/4b6f2c28-129e-4cb7-8a56-7b6161411596) | ![image](https://github.com/user-attachments/assets/2258321c-7d20-4c91-b9c8-0e8f1b2a63de) |

chore(design): Add form demo for Modal and Card

---

docs/codemod/codemod-CHANGELOG.md
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2025-02-05`
- 🔥 新增 11 篇设计规范文档，包括 5 篇设计原则、6 篇设计基础。[#954](https://github.com/oceanbase/oceanbase-design/pull/954)
- 🔥 新增 6 篇组件规范文档，包括 Alert、Button、Tabs、Table、Modal 和 DateRanger。[#955](https://github.com/oceanbase/oceanbase-design/pull/955)
- 📖 优化官网在移动端的样式和访问体验。[#956](https://github.com/oceanbase/oceanbase-design/pull/956)
- 💄 默认去掉 Form.Item 包裹 Switch 时的可选样式。[#949](https://github.com/oceanbase/oceanbase-design/pull/949)
- 💄 优化 Table 空状态的高度，大中小尺寸分别为 360px、260px 和 160px。[#947](https://github.com/oceanbase/oceanbase-design/pull/947)
---
`2025-02-05`
- DateRanger
- 🆕 DateRanger 支持自定义快捷选项。[#952](https://github.com/oceanbase/oceanbase-design/pull/952)
- ⭐️ DateRanger 支持自动校验和交换起止时间。[#953](https://github.com/oceanbase/oceanbase-design/pull/953)
- 💄 优化 ProTable 间距，以对齐 Table 在 Card …

chore(docs): Add changelog for @oceanbase/design@0.4.7, @oceanbase/ui@0.4.8 and @oceanbase/codemod@0.4.7

---

packages/ui/src/DateRanger/Ranger.tsx
packages/ui/src/DateRanger/index.md

特殊场景需要做单独适配，目前无法自定义时间选择面板的样式，因此添加两个参数用于自定义时间选择面板的样式。
使用：
```tsx
<DateRanger
overlayClassName="overlay-custom-date-ranger"
overlayStyle={{ color: 'red' }}
/>
```
| 🇺🇸 English | add overlayClassName and overlayStyle props |
| 🇨🇳 Chinese | - 🆕 DateRanger 新增 `overlayClassName` 和 `overlayStyle` 属性，用于设置弹出面板的样式。  |

feat(ui): [date-ranger] add overlayClassName and overlayStyle props

---

docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2025-02-13`
- 📖 优化设计基础、设计原则和组件设计文档的内容和样式。[#966](https://github.com/oceanbase/oceanbase-design/pull/966)
- 🐞 修复 `@ctrl/tinycolor` 依赖缺失的问题。[#973](https://github.com/oceanbase/oceanbase-design/pull/973)
- Tooltip:
- 🔨 去掉 Tooltip `mouseFollow` 模式下控制台出现的 NaN 告警。[#968](https://github.com/oceanbase/oceanbase-design/pull/968)
- 🔨 将 [react-sticky-mouse-tooltip](https://github.com/marlo22/react-sticky-mouse-tooltip) 代码内置到 Tooltip，避免控制台告警和错误都指向 `MouseTooltip.jsx`、干扰问题排查。[#969](https://github.com/oceanbase/oceanbase-design/pull/969)
---
`2025-02-13`
- DateRanger
- 🆕 DateRanger 新增 `autoAdjustOverflow` 属性，用于控制弹出面板是否自动调整位置。[#972](https://github.com/oceanbase/oceanbase-design/pull/972) [@wzc520pyfm](https://github.com/wzc520pyfm)
- 🆕 DateRanger 新增 `overlayClassName` 和 `overlayStyle` …

chore(docs): Add changelog for @oceanbase/design@0.4.8 and @oceanbase/ui@0.4.9

---

docs/design/design-CHANGELOG.md

`2025-02-20`
- 📖 Table 设计文档新增 高亮显式 规范。[#986](https://github.com/oceanbase/oceanbase-design/pull/986)
- 📖 Typography 新增可复制和在 Modal 中编辑的示例。[#985](https://github.com/oceanbase/oceanbase-design/pull/985)
- ⭐️ ConfigProvider 移除 `injectStaticFunction` 属性，改为自动判断是否注入可消费全局配置的静态方法。[#981](https://github.com/oceanbase/oceanbase-design/pull/981)
- Table
- 🐞 修复 Table 可展开&固定列时的间距问题。[#982](https://github.com/oceanbase/oceanbase-design/pull/982)
- 🐞 修复 Table 可展开&可滚动时不应该展示斑马条的问题。[#983](https://github.com/oceanbase/oceanbase-design/pull/983)
- 💄 Alert 改为使用线性图标，以对齐最新的设计规范。[#987](https://github.com/oceanbase/oceanbase-design/pull/987)
- 💄 Dropdown.Button 默认图标改为 `DownOutlined` 向下箭头。[#984](https://github.com/oceanbase/oceanbase-design/pull/984)

chore(docs): Add changelog for @oceanbase/design@0.4.9

---

.dumirc.ts
docs/design/design-CHANGELOG.md
packages/design/src/auto-complete/demo/basic.tsx
packages/design/src/auto-complete/demo/non-case-sensitive.tsx
packages/design/src/auto-complete/index.md

- None
| 🇨🇳 Chinese | - 📖 新增 AutoComplete 的示例和文档。          |

docs(design): Add docs and demo for AutoComplete

---

packages/design/src/form/FormItem.tsx
packages/design/src/form/__tests__/__snapshots__/item.test.tsx.snap
packages/design/src/form/__tests__/item.test.tsx
packages/design/src/form/demo/form-item-action.tsx
packages/design/src/form/demo/form-item-tooltip.tsx
packages/design/src/form/demo/hideRequiredMark.tsx
packages/design/src/form/demo/requiredMark-same-with-antd.tsx
packages/design/src/form/index.md
packages/design/src/form/style/index.ts

- None
| 🇨🇳 Chinese | - 🆕 Form.Item 新增 `action` 属性，用于设置操作项。          |

feat(design): vertical Form.Item add action prop

---

docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md
packages/design/src/form/demo/form-item-action.tsx

`2024-04-18`
- 📖 新增 AutoComplete 的示例和文档。[#1012](https://github.com/oceanbase/oceanbase-design/pull/1012)
- 📖 新增 Anchor 的文档和示例。[#1013](https://github.com/oceanbase/oceanbase-design/pull/1013)
- 📖 新增 Steps 的文档和示例。[#1014](https://github.com/oceanbase/oceanbase-design/pull/1014)
- 📖 新增 Menu 的文档和示例。[#1015](https://github.com/oceanbase/oceanbase-design/pull/1015)
- 📖 新增 Pagination 的文档和示例。[#1016](https://github.com/oceanbase/oceanbase-design/pull/1016)
- 📖 新增 Upload 的文档和示例。[#1017](https://github.com/oceanbase/oceanbase-design/pull/1017)
- 📖 新增 Tree 的文档和示例。[#1018](https://github.com/oceanbase/oceanbase-design/pull/1018)
- 📖 新增 TreeSelect 的文档和示例。[#1019](https://github.com/oceanbase/oceanbase-design/pull/1019)
- 📖 [图标] 展示更多的图标。[#1024](https://github.com/oceanbase/oceanbase-design/pull/1024)
- 🆕 …

chore(docs): Add changelog for @oceanbase/design@0.4.10 and @oceanbase/ui@0.4.12

---

packages/ui/src/DateRanger/Ranger.tsx

Omit the style prop form the params passed to antd picker.
外部传进来的 `style` 和 `className` 参数应当仅作用于`DateRanger` 跟组件，不应该传入到`DatePicker.RangePicker` 
| 🇺🇸 English | - fix(ui): [date-ranger]: omit the style and className prop form the params passed to antd picker.  |
| 🇨🇳 Chinese | - 🐞 修复 DateRanger `style` 和 `className` 应该仅对根组件生效、不应该对 RangePicker 生效的问题。  |

fix(ui): [date-ranger]: omit style and className prop form params passed to antd picker

---

packages/ui/src/DateRanger/Ranger.tsx

一些场景下存在滚动问题（Modal空间不足时打开浮层无法滚动），希望可以自定义浮层容器位置
| 🇺🇸 English | support set getPopupContainer prop |
| 🇨🇳 Chinese | - 🆕 DateRanger 新增 `getPopupContainer` 属性，用于设置弹出面板的挂载容器。 |

feat(ui): [date-ranger] support set getPopupContainer prop

---

packages/charts/src/Line/demo/mul-gradient-fill.tsx
packages/charts/src/Line/index.md
packages/charts/src/Line/index.tsx

期望Line图表支持渐变色填充。
现在只需要传递 <Line area={ gradientFill: true } /> 就可开启渐变填充。
Preview:
| 🇺🇸 English | - 🆕 Line chart add `area.gradientFill` prop for gradient fill area. |
| 🇨🇳 Chinese | - 🆕 Line 新增 `area.gradientFill` 属性，用于设置渐变面积图。 |

feat(charts): Line chart add area.gradientFill prop for gradient fill area

---

docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2025-07-10`
- 🐞 修复 `boxShadow` 相关 Design Token 不正确的问题。[#1096](https://github.com/oceanbase/oceanbase-design/pull/1096)
- 💄 更新 boxShadowTertiary token 的值。[#1097](https://github.com/oceanbase/oceanbase-design/pull/1097)
---
`2025-07-10`
- 💄 Login 的背景图片居中展示。[#1094](https://github.com/oceanbase/oceanbase-design/pull/1094)
- 💄 将 DateRanger 快捷选项的背景色从透明调整为白色。[#1095](https://github.com/oceanbase/oceanbase-design/pull/1095) [@wzc520pyfm](https://github.com/wzc520pyfm)

chore(docs): Add changelog for @oceanbase/design@0.4.12 and @oceanbase/ui@0.4.15

---

docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2025-07-27`
- 🆕 Segmented `options` 新增 `badge` 属性，用于设置选项卡后面的徽标。[#1100](https://github.com/oceanbase/oceanbase-design/pull/1100) [@wzc520pyfm](https://github.com/wzc520pyfm)
- 🆕 Tabs `options` 新增 `badge` 属性，用于设置选项卡后面的徽标。原 `tag` 属性标记为即将废弃，后续不推荐使用。[#1110](https://github.com/oceanbase/oceanbase-design/pull/1110) [@wzc520pyfm](https://github.com/wzc520pyfm)
- 💄 优化 Slider 在最大值和最小值相等时的 `marks` 样式。[#1105](https://github.com/oceanbase/oceanbase-design/pull/1105)
`2025-07-27`
- 💄 ProCard 折叠图标使用实心箭头、图标颜色改为二级文本色。[#1111](https://github.com/oceanbase/oceanbase-design/pull/1111) [@wzc520pyfm](https://github.com/wzc520pyfm)

chore(docs): Add changelog for @oceanbase/design@0.4.13 and @oceanbase/ui@0.4.16

---

docs/codemod/codemod-CHANGELOG.md
docs/design/design-CHANGELOG.md
docs/ui/ui-CHANGELOG.md

`2025-09-24`
- Design Token
- 🌈 更新 `fontSizeLG` 和 `fontSizeHeading` 字体大小。[#1200](https://github.com/oceanbase/oceanbase-design/pull/1200)
- 🌈 更新 `controlHeight` 控件高度 `32` => `28`。[#1201](https://github.com/oceanbase/oceanbase-design/pull/1201)
- 🌈 更新 `borderRadiusLG` 大号圆角 `6` => `8`。[#1206](https://github.com/oceanbase/oceanbase-design/pull/1206)
- 🌈 更新 Table `cellPaddingBlock` 单元格纵向间距。[#1208](https://github.com/oceanbase/oceanbase-design/pull/1208)
- Badge
- 🐞 修复 Badge 状态文本字体大小不会继承父元素的问题，便于和其他组件组合使用。[#1214](https://github.com/oceanbase/oceanbase-design/pull/1214)
- 💄 调整 Badge `processing` 态的颜色和圆点大小。[#1205](https://github.com/oceanbase/oceanbase-design/pull/1205)
- Card
- 💄 Card `tabs` 默认尺寸改为 `middle`。[#1216](https://github.com/oceanbase/oceanbase-design/pull/1216)
- 💄 优化 Card …

[v1] chore(docs): Add changelog for @oceanbase/design@1.0.0-alpha.2, @oceanbase/ui@1.0.0-alpha.2 and @oceanbase/codemod@1.0.0-alpha.2
