.github/workflows/site-deploy.yml, CNAME, docs/ui/ui-quickstart.md
- CNAME: `design.oceanbase.com`
- Other update: Fix CodeSandbox demo for `@oceanbase/ui`
=> chore(site): Add CNAME

packages/ui/src/BackgroundTaskManager/demo/NotificationCenter.tsx, packages/ui/src/BackgroundTaskManager/demo/NotificationCenterDemo.tsx
Failed to load the official website sample: [BackgroundTaskManagerDemo](https://design.oceanbase.com/biz-components/background-task-manager).
=> fix(ui): [background-task-manager] fix demo error

.dumi/theme/slots/Content/index.tsx
close https://github.com/oceanbase/oceanbase-design/issues/7
=> fix(doc): [theme] fix description was repeated

.dumirc.ts
- ref: https://d.umijs.org/config#sitemap
=> config(site): Enable sitemap for SEO

packages/ui/src/Action/Item.tsx
=> fix(ui): Action click error

.github/dependabot.yml
- Allow Dependabot to open pull requests automatically to keep your dependencies up-to-date when new versions are available.
- ref: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
=> feat(workflow): Create dependabot.yml

packages/design/package.json, packages/design/src/input-number/demo/addon.tsx, packages/design/src/input-number/demo/basic.tsx, packages/design/src/input-number/demo/formatter.tsx, packages/design/src/input-number/demo/status.tsx, packages/design/src/table/demo/dynamic-settings.tsx, packages/design/src/table/demo/multiple-nesting-tables.tsx, packages/design/src/table/demo/nesting-tables.tsx, packages/ui/src/BasicLayout/demo/banner.tsx, packages/ui/src/BasicLayout/demo/basic.tsx, packages/ui/src/BasicLayout/demo/no-sider-and-custom-header.tsx, packages/ui/src/BasicLayout/demo/subSideMenu.tsx, packages/ui/src/BasicLayout/demo/topHeader-icon.tsx, packages/ui/src/BasicLayout/demo/topHeader-title.tsx, packages/ui/src/BasicLayout/demo/welcome.tsx, packages/ui/src/PageContainer/demo/basic.tsx, packages/ui/src/PageContainer/demo/complete.tsx, packages/ui/src/SideTip/demo/backTop.tsx, packages/ui/src/SideTip/demo/basic.tsx, packages/ui/src/SideTip/demo/content.tsx, packages/ui/src/SideTip/demo/disabled.tsx, packages/ui/src/SideTip/demo/loading.tsx, packages/ui/src/SideTip/demo/modal.tsx, packages/ui/src/SideTip/demo/normal.tsx, packages/ui/src/SideTip/demo/operation.tsx, packages/ui/src/SideTip/demo/small.tsx, packages/ui/src/SideTip/demo/tooltip.tsx, packages/ui/src/TreeSearch/demo/customTitle.tsx, pnpm-lock.yaml
- @ant-design/icons => @oceanbase/icons
=> chore(design & ui): @ant-design/icons => @oceanbase/icons

packages/design/src/tooltip/index.tsx
=> fix(tooltip): color prop should work

.github/dependabot.yml, package.json, packages/charts/package.json, packages/design/package.json, packages/ui/package.json, packages/ui/src/BasicLayout/index.md, packages/ui/src/PageContainer/index.md, packages/util/package.json, packages/util/src/hooks/useQuery.ts, packages/util/src/hooks/useScrollToPosition.ts, packages/util/src/util/index.ts, plugin-theme-less.ts
- @oceanbase/charts@0.2.7
- @oceanbase/design@0.2.13
- @oceanbase/ui@0.2.14
- @oceanbase/util@0.2.5
- updates ignore execa
=> chore: Publish versions, improve docs and dependabot update ignore execa

packages/design/src/_util/genComponentStyleHook.ts, packages/design/src/config-provider/__tests__/__snapshots__/spin.test.tsx.snap, packages/design/src/config-provider/__tests__/spin.test.tsx, packages/design/src/config-provider/demo/spin.tsx, packages/design/src/config-provider/index.md, packages/design/src/config-provider/index.tsx, packages/design/src/spin/demo/custom-indicator.tsx, packages/design/src/spin/index.tsx, pnpm-lock.yaml
=> feat(design): Support spin.indicator for ConfigProvider

packages/design/src/modal/demo/over-height.tsx, packages/design/src/modal/demo/static-function.tsx, packages/design/src/modal/index.md, packages/design/src/modal/index.tsx, packages/design/src/modal/style/index.ts, packages/design/src/spin/demo/inside.tsx, packages/design/src/spin/demo/tip.tsx
=> feat(design): New style for Modal

packages/design/src/tooltip/index.tsx
| Previous | After |
|  ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/10e0a130-ed8d-45ba-9b42-7bbe086a4614) |  ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/e29fc30d-a189-478e-95a5-8b6b0cf40fad) |
=> improve(design): Tooltip light style in dark theme

packages/design/package.json, pnpm-lock.yaml
=> fix(design): Add missing prop-types dep

.dumirc.ts, packages/ui/src/ContentWithQuestion/__test__/index.test.tsx, packages/ui/src/ContentWithQuestion/demo/basic.tsx, packages/ui/src/ContentWithQuestion/demo/index.less, packages/ui/src/ContentWithQuestion/demo/prefix.tsx, packages/ui/src/ContentWithQuestion/index.less, packages/ui/src/ContentWithQuestion/index.md, packages/ui/src/ContentWithQuestion/index.tsx, packages/ui/src/index.ts
=> feat(ContentWithQuestion):  add ContentWithQuestion

packages/ui/src/PageContainer/demo/basic.tsx, packages/ui/src/PageContainer/demo/header-less.tsx, packages/ui/src/PageContainer/index.tsx, packages/ui/src/PageContainer/style/index.ts
=> fix(ui): reload should work when subTitle is null

packages/design/src/table/demo/fixed-columns-header-tables.tsx, packages/design/src/table/style/index.ts
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/835f09f1-35bb-4b91-8030-8e642e1ac5c8) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/81af526d-15a2-468b-a42a-11492ab305b9) |
=> fix(design): zebra stripe style should be correct for scroll table

packages/codemod/transforms/__testfixtures__/obui-to-oceanbase-design-and-ui/locale.input.js, packages/codemod/transforms/__testfixtures__/obui-to-oceanbase-design-and-ui/locale.output.js, packages/codemod/transforms/__testfixtures__/obui-to-oceanbase-design-and-ui/obui.input.js, packages/codemod/transforms/__testfixtures__/obui-to-oceanbase-design-and-ui/obui.output.js, packages/codemod/transforms/__tests__/obui-to-oceanbase-design-and-ui.test.ts, packages/codemod/transforms/obui-to-oceanbase-design-and-ui.js, packages/codemod/transforms/utils/import-component.js
```diff
- import enUS from '@alipay/ob-ui/es/locale/en-US';
- import zhCN from '@alipay/ob-ui/es/locale/zh-CN';
+ import enUS from '@oceanbase/ui/es/locale/en-US';
+ import zhCN from '@oceanbase/ui/es/locale/zh-CN';
```
=> improve(codemod): @alipay/ob-ui => @oceanbase/ui for locale

packages/design/src/table/demo/edit-row.tsx, packages/design/src/table/index.md, packages/design/src/table/index.tsx
=> fix(design): Table columns maybe undefined and add edit-row demo for Table

packages/codemod/README.md, packages/codemod/bin/cli.js, packages/codemod/transforms/__testfixtures__/style-to-token/class-component.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/class-component.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/function-component.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/function-component.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/static.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/static.output.js, packages/codemod/transforms/__tests__/style-to-token.test.ts, packages/codemod/transforms/style-to-token.js, packages/codemod/transforms/utils/index.js
- Ref: #60
- `style-to-token` transform
=> feat(codemod): Add style-to-token transform

packages/codemod/bin/cli.js, packages/codemod/package.json, packages/codemod/transforms/__testfixtures__/less-to-token/antd-v4-less-to-token.input.less, packages/codemod/transforms/__testfixtures__/less-to-token/antd-v4-less-to-token.output.less, packages/codemod/transforms/__testfixtures__/less-to-token/obui-less-to-token.input.less, packages/codemod/transforms/__testfixtures__/less-to-token/obui-less-to-token.output.less, packages/codemod/transforms/__tests__/less-to-token.test.ts, packages/codemod/transforms/less-to-token.js, packages/codemod/transforms/style-to-token.js, packages/codemod/transforms/utils/token.js, pnpm-lock.yaml
- Ref: #60
- `less-to-token` transform:
=> feat(codemod): Add less-to-token transform

packages/codemod/transforms/__testfixtures__/less-to-token/antd-v4-less-to-token.input.less, packages/codemod/transforms/__testfixtures__/less-to-token/antd-v4-less-to-token.output.less, packages/codemod/transforms/__testfixtures__/less-to-token/obui-less-to-token.input.less, packages/codemod/transforms/__testfixtures__/less-to-token/obui-less-to-token.output.less, packages/codemod/transforms/utils/token.js
=> feat(codemod): TOKEN_MAP add obui style

.github/workflows/release-helper.yml
- GitHub Action: https://github.com/marketplace/actions/monorepo-release-helper
=> config(workflow): Use new params for release-helper

packages/codemod/transforms/__testfixtures__/less-to-token/antd-v4-less-to-token.input.less, packages/codemod/transforms/__testfixtures__/less-to-token/antd-v4-less-to-token.output.less, packages/codemod/transforms/__testfixtures__/style-to-token/function-component.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/function-component.output.js, packages/codemod/transforms/utils/token.js
=> fix(codemod): token priority should be #ffffff > #fff

packages/codemod/README.md, packages/codemod/transforms/__testfixtures__/style-to-token/function-component.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/function-component.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/static.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/static.output.js, packages/codemod/transforms/style-to-token.js
=> fix(codemod): style-to-token should add {} wrapper for JSXAttribute

packages/codemod/transforms/less-to-token.js
=> fix(codemod): file path should be correct

.github/PULL_REQUEST_TEMPLATE.md
=> feat(github): Add PULL_REQUEST_TEMPLATE.md

packages/codemod/transforms/__testfixtures__/style-to-token/existed-useToken.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/existed-useToken.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/multiple-block-statement.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/multiple-block-statement.output.js, packages/codemod/transforms/__tests__/style-to-token.test.ts, packages/codemod/transforms/style-to-token.js
- None.
- should not insert `const { token } = theme.useToken();`
| 🇺🇸 English |  🐞 Fix duplicate `const { token } = theme.useToken();` for nested block statement or when it's existed.        |
| 🇨🇳 Chinese | 🐞 修复 `const { token } = theme.useToken();` 被重复声明的问题。           |
=> fix(codemod): should avoid duplicate `const { token } = theme.useToken();`

docs/charts/charts-migrate-from-ant-design-charts.md, docs/design/design-migrate-from-antd.md, docs/design/design-migrate-from-obui.md, docs/ui/ui-migrate-from-obui.md, packages/codemod/README.md
- None.
| 🇺🇸 English |   📖 Add auto migration docs for @oceanbase/design, @oceanbase/ui and @oceanbase/charts. [#243](https://github.com/oceanbase/oceanbase-design/pull/243)       |
| 🇨🇳 Chinese |  📖  新增 @oceanbase/design、@oceanbase/ui 和 @oceanbase/charts 的自动化迁移文档。[#243](https://github.com/oceanbase/oceanbase-design/pull/243)        |
=> feat(docs): Add auto migration docs for @oceanbase/design, @oceanbase/ui and @oceanbase/charts

packages/ui/src/BackgroundTaskManager/demo/NotificationCenter.tsx, packages/ui/src/BackgroundTaskManager/index.tsx
完善 Demo 的逻辑，支持手动关闭 notification
=> fix(): 对任务管理的 notification 补充 key 值和手动关闭操作

packages/codemod/README.md, packages/codemod/transforms/__testfixtures__/less-to-token/antd-v4-less-to-token.input.less, packages/codemod/transforms/__testfixtures__/less-to-token/case-insensitive.input.less, packages/codemod/transforms/__testfixtures__/less-to-token/case-insensitive.output.less, packages/codemod/transforms/__testfixtures__/style-to-token/case-insensitive.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/case-insensitive.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/statement.input.js, packages/codemod/transforms/__tests__/less-to-token.test.ts, packages/codemod/transforms/__tests__/style-to-token.test.ts, packages/codemod/transforms/utils/token.js
- TOKEN_MAP key should be lower case for replace style to token correctly.
| 🇺🇸 English |   🐞 Fix part of case-sensitive style not transform to token. [#244](https://github.com/oceanbase/oceanbase-design/pull/244)         |
| 🇨🇳 Chinese | 🐞 修复部分样式由于大小写敏感没有被改写为 token 的问题。[#244](https://github.com/oceanbase/oceanbase-design/pull/244)          |
=> fix(codemod): TOKEN_MAP key should be lower case

packages/ui/src/BasicLayout/Header.tsx, packages/ui/src/BasicLayout/style/Header.ts, packages/ui/src/LocaleDropdown/index.tsx, packages/ui/src/Login/index.tsx
- None
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/829d9381-f02a-4cd7-97a2-61fa1f050dc2) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/5ed9fcd3-32da-45ce-ae64-83d7a9a59af8) |
| 🇺🇸 English |  🐞 Fix BasicLayout locale switch font size is too large.           |
| 🇨🇳 Chinese | 🐞 修复 BasicLayout 顶部语言切换的字体大小偏大的问题。          |
=> fix(ui): BasicLayout locale switch font size is too large

packages/codemod/transforms/__testfixtures__/less-to-token/mixin.input.less, packages/codemod/transforms/__testfixtures__/less-to-token/mixin.output.less, packages/codemod/transforms/__tests__/less-to-token.test.ts, packages/codemod/transforms/less-to-token.js
- None
| 🇺🇸 English |  🐞 Fix less function `.mixin()` transform to `@mixin()` incorrectly.       |
| 🇨🇳 Chinese |  🐞 修复 less 函数 `.mixin()` 被错误改写为 `@mixin()` 的问题。         |
=> fix(codemod): .mixin() should not transform to @mixin() for less-to-token

packages/ui/src/TagSelect/style/index.ts
| 🇺🇸 English |   improve click style for TagSelect       |
| 🇨🇳 Chinese | 优化组件点击样式     |
=> improve(TagSelect): improve click style

packages/codemod/README.md, packages/codemod/bin/cli.js
| 🇺🇸 English |  🆕 Add `--transformer` command option for specify target transformers.         |
| 🇨🇳 Chinese | 🆕 新增 `--transformer` 命令行参数，用于指定要运行的转换脚本。          |
=> feat(codemod): Add `--transformer` command option for specify target transformers

packages/design/src/config-provider/__tests__/theme.test.tsx, packages/design/src/spin/index.tsx, packages/ui/src/PageContainer/demo/basic.tsx, packages/ui/src/PageContainer/demo/complete.tsx
- #251
- @oceanbase/design
- @oceanbase/ui
| 🇺🇸 English |   🆕  Set Spin default indicator to OceanBase animation.        |
| 🇨🇳 Chinese |  🆕 全局设置 Spin 的加载指示符为 OceanBase 加载动画。          |
=> feat(design): set Spin default indicator to work globally

packages/ui/src/Login/demo/activate.tsx, packages/ui/src/Login/demo/authCode.tsx, packages/ui/src/Login/demo/bg-image.tsx, packages/ui/src/Login/demo/otherLogin.tsx, packages/ui/src/Login/demo/with-alert.tsx, packages/ui/src/Login/index.less, packages/ui/src/Login/index.md
- None
| 1535px | 1791px | 2047px |
| :--- | :--- | :--- |
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/e3e75497-bcbc-45b7-872d-806ffc36952d) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/1fc50ade-60d6-4662-9ece-39ecff65dd84) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/47d4b128-57b3-4ec0-a95a-9f641340c3d0) | 
| 🇺🇸 English | 💄 Improve Login style in different screen size.         |
| 🇨🇳 Chinese |  💄 优化 Login 在不同屏幕尺寸下的样式。         |
=> improve(ui): Login style in different screen size

packages/design/src/modal/style/index.ts
- None
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/6eb31e26-203c-4f2e-9d9a-0c6c54649423) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/570c27e7-1c4e-4973-8ffe-76b9a99c6e1c) |
| 🇺🇸 English |  💄 Improve Modal confirm content style.        |
| 🇨🇳 Chinese |  💄 优化 Modal 确认对话框的内容区样式。         |
=> improve(design): Modal confirm content style

packages/design/src/drawer/Drawer.tsx, packages/design/src/drawer/demo/footer.tsx, packages/design/src/drawer/demo/over-height.tsx, packages/design/src/drawer/index.md, packages/design/src/drawer/style/index.ts
=> fix(design): Drawer should add `${componentCls}-content` wrapper to overwritten antd style

packages/charts/src/ChartProvider/__tests__/theme.test.tsx, packages/charts/src/theme/dark.ts, packages/charts/src/theme/light.ts
- None
| 🇺🇸 English |  🌈 Update qualitative and semantic palette for light and dark theme.          |
| 🇨🇳 Chinese |  🌈 更新浅色主题和暗色主题的分类色板和语义色板。         |
=> 🌈 improve(charts): Update palette for light and dark theme

packages/design/src/descriptions/index.tsx, packages/design/src/form/FormItem.tsx, packages/design/src/form/index.ts, packages/design/src/index.ts
- Fix #308
| 🇺🇸 English |  🤖 Export extended components' type definition, including AlertProps, CardProps, ConfigProviderProps, DescriptionsItemProps, FormItemProps, ModalProps, ModalProgressProps, DrawerProps, TableProps, TabsProps, TagProps, TooltipProps, SpinProps and BadgeProps。         |
| 🇨🇳 Chinese |  🤖 导出 AlertProps、CardProps、ConfigProviderProps、DescriptionsItemProps、FormItemProps、ModalProps、ModalProgressProps、DrawerProps、TableProps、TabsProps、TagProps、TooltipProps、SpinProps 和 BadgeProps 等扩展组件的 TS 类型。   |
=> feat(design): Export extended components' TypeScript definition

packages/design/src/config-provider/index.tsx, packages/design/src/drawer/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/drawer/__tests__/index.test.tsx, packages/design/src/drawer/demo/custom-footer.tsx, packages/design/src/drawer/demo/descriptions.tsx, packages/design/src/drawer/demo/form-drawer.tsx, packages/design/src/drawer/demo/over-height.tsx, packages/design/src/drawer/index.md, packages/design/src/drawer/index.ts, packages/design/src/drawer/index.tsx, packages/design/src/drawer/style/index.ts, packages/design/src/locale/index.ts
- None
| 调整 | 设计稿 |
| 间距   | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/e24041f7-3a5b-4086-9c93-acf99e0850d4) |
| 长表单 | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/220dae30-3519-4990-a52f-72f543324cf3) |
| 短表单 | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/220dae30-3519-4990-a52f-72f543324cf3) |
| 投影 | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/8ea64806-2600-4fd6-8e9d-c53dd622ab62) |
| 🇨🇳 Chinese |  🌈 实现新版 Drawer 的交互和样式，包括: 1. 优化页头/内容区/页脚的间距 2. 当内容高度大于等于抽屉高度时，页脚会置底展示；当内容高度小于抽屉高度时，footer 会跟随内容展示 3. 页脚操作区的主按钮位置居左。         |
⚠️ Please check all items below before requesting a reviewing. …
=> improve(design): Update Drawer design rules of padding, footer and scroll

packages/design/src/form/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/form/__tests__/index.test.tsx, packages/design/src/form/demo/form-item-tooltip.tsx, packages/design/src/form/index.tsx
- Fix 312
| 🇺🇸 English |  🐞 Fix Form `requiredMark` not inherit from ConfigProvider.          |
| 🇨🇳 Chinese |  🐞 修复 Form `requiredMark` 没有继承 ConfigProvider 全局配置的问题。        |
=> fix(design): Form requiredMark should inherit from ConfigProvider

.dumi/theme/common/Loading.tsx, .dumirc.ts, packages/design/src/descriptions/index.tsx, packages/design/src/drawer/index.tsx, packages/design/src/index.ts, packages/design/src/segmented/index.tsx, packages/design/src/table/index.tsx, packages/design/src/tag/index.tsx, packages/design/src/typography/Link.tsx, packages/design/src/typography/Paragraph.tsx, packages/design/src/typography/Text.tsx, packages/design/src/typography/Title.tsx, packages/design/src/typography/demo/inner.tsx, packages/design/src/typography/demo/text.tsx, packages/design/src/typography/index.md, packages/design/src/typography/index.ts, packages/design/src/typography/style/index.ts
- Fix #284
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/2183cded-91f4-4e0b-b0b7-5c7f3fa8f1c7) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/d4300cc8-4301-4006-87d2-cba508b12143) |
| 🇺🇸 English |     -      |
| 🇨🇳 Chinese |  💄 Typography.Text 和 Typography.Paragraph 的默认字体颜色和行高，会继承父元素的设置，而不总是 `token.colorText` 和 `token.lineHeight`，以解决和其他组件组合使用的问题。         |
=> improve(design): Typography.Text and Typography.Paragraph default color and line-height should inherit from parent

packages/design/src/badge/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/badge/demo/count-independent.tsx, packages/design/src/badge/demo/count.tsx, packages/design/src/badge/demo/dot.tsx, packages/design/src/badge/demo/ribbon.tsx, packages/design/src/badge/demo/status-inner.tsx, packages/design/src/badge/index.md, packages/design/src/badge/index.tsx, packages/design/src/badge/style/index.ts, packages/design/src/typography/index.md, packages/design/src/typography/style/index.ts
- Fix #284
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/cc607736-6091-4939-ac8a-96ed4db42515) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/7d7ffccb-2e96-4c91-b5d6-9d26330ed5cd) |
| 🇨🇳 Chinese |  💄 Badge 状态文本的默认字体颜色，会继承父元素的设置，而不总是 `token.colorText`，便于和其他组件组合使用。         |
=> improve(design): Badge status text default color should inherit from parent

package.json, packages/design/src/_util/getEllipsisConfig.ts, packages/design/src/descriptions/hooks/useItems.tsx, packages/design/src/tag/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/tag/__tests__/index.test.tsx, packages/design/src/tag/demo/ellipsis.tsx, packages/design/src/tag/index.md, packages/design/src/tag/index.tsx, packages/design/src/tag/style/index.ts, pnpm-lock.yaml, tests/util.ts
- None.
| Container Width | Specific Width & Custom Tooltip |
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/a7eddf68-eca9-4945-9e7d-98bcebe60329) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/5ec6638a-2a4d-40fc-85f1-614d72ed7f1c) |
| 🇺🇸 English |  🆕 Tag add `ellipsis` prop to configure overflow content and Tooltip.        |
| 🇨🇳 Chinese | 🆕 Tag 新增 `ellipsis` 属性，用于配置内容溢出时的省略和 Tooltip 提示。          |
=> feat(design): Tag add Typography.Text ellipsis prop

packages/ui/src/BasicLayout/index.md
- Fix #362.
| 🇺🇸 English |  📝 Add BasicLayout `location` prop usage.         |
| 🇨🇳 Chinese | 📝 新增 BasicLayout `location` 属性的用法说明，即用于实现选中菜单和当前路由之间的联动。          |
=> 📝 improve(docs): Add BasicLayout location prop usage

packages/ui/src/BasicLayout/index.tsx
- None.
| 🇺🇸 English | 💄 BasicLayout support to set open menus auto according to pathname.         |
| 🇨🇳 Chinese |  💄 BasicLayout 支持根据当前路由自动设置展开菜单项。         |
=> 💄 improve(ui): BasicLayout support to set open menus auto according to pathname

packages/ui/src/TagSelect/style/index.ts
使用 token 优化样式，还原设计细节
| change   | before |  after | 
| ---------- | --------- | ------- | 
| disabled | ![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/d19a266d-e17d-4398-83d0-0d0e730d469b) |  ![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/f84bcc95-5f90-4405-9dbf-a2d89e59ee08) | 
| hover | ![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/3c936d70-427d-4b00-b67d-acd2d7695f0d) | ![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/0eb96c76-5b30-4163-ae71-a2c04b210ef3) | 
| padding | ![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/63846a3c-dd46-487d-9369-f7a7fafd2864) | ![image](https://github.com/oceanbase/oceanbase-design/assets/62171869/4cc47a2a-4da3-449f-ab26-493176c95dd6) |
| …
=> improve(TagSelect): fixed style => design token

packages/ui/src/BasicLayout/demo/IconFont.tsx, packages/ui/src/BasicLayout/demo/banner.tsx, packages/ui/src/BasicLayout/demo/basic.tsx, packages/ui/src/BasicLayout/demo/menu-over-length.tsx, packages/ui/src/BasicLayout/demo/subSideMenu.tsx, packages/ui/src/BasicLayout/demo/topHeader-icon.tsx, packages/ui/src/BasicLayout/demo/topHeader-title.tsx, packages/ui/src/BasicLayout/demo/welcome.tsx, packages/ui/src/IconFont/index.tsx
- Fix #372
| 🇨🇳 Chinese |  🐞 修复 IconFont 会请求不必要 JS 资源的问题。📢 将 IconFont 组件标记为即将废弃，不推荐使用。         |
=> fix(ui): Remove IconFont built-in script url and mark IconFont as @deprecated

packages/design/src/theme/style/compact.less, packages/design/src/theme/style/dark.less, packages/design/src/theme/style/default.less
- None
| 🇨🇳 Chinese | 💄 更新 Design Token，新增 `fontHeight`、`fontHeightLG` 和 `fontHeightSM` less 变量。         |
=> improve(design): Update less variables of design token

packages/charts/src/Column/index.tsx
- None
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/cf4b4bea-66d6-4f2f-b393-0392888e8d3d) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/8f330840-13c1-463e-be77-5e50282cd4d5) |
| 🇨🇳 Chinese |  💄 Column 适配 X 时序轴，自动对数据进行排序，并关闭自动美化，避免两侧留白。         |
=> improve(charts): Column adapt to time xAxis and default legend marker change to square

packages/charts/src/Liquid/index.tsx
- Result by https://github.com/oceanbase/oceanbase-design/pull/374 where fixed `height: 400` is removed.
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/3d6eb505-eda7-4b2a-a6ee-45c6f2dde439) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/ca627438-a8da-489c-a87f-f2dfb3c243ef) |
| 🇺🇸 English | 🐞 Fix Liquid wave not render when height is null.         |
| 🇨🇳 Chinese | 🐞 修复 Liquid 未设置高度时水波无法渲染的问题。         |
=> fix(charts): Liquid wave should render when height is null

.github/PULL_REQUEST_TEMPLATE.md, packages/charts/src/Stat/index.md, packages/charts/src/Stat/index.tsx
- None
| 🇺🇸 English |  🆕 Stat add `chartConfig` prop to configure chart.        |
| 🇨🇳 Chinese | 🆕 Stat 新增 `chartConfig` 属性，用于配置图表。         |
=> feat(charts): Stat add chartConfig prop to configure tiny area

packages/charts/src/Stat/index.less, packages/charts/src/Stat/index.tsx, packages/charts/src/util/measureText.ts
- None
| 🇨🇳 Chinese |  💄 优化 Stat 样式，包括限制 title 字体最小为 12px、限制 value 字体最大为 40px以及优化内容居中对齐样式。        |
=> improve(charts): Stat style, including title size, value size and center align

packages/design/src/config-provider/__tests__/__snapshots__/prefixCls.tsx.snap, packages/design/src/config-provider/__tests__/prefixCls.tsx
- None
- None
| 🇨🇳 Chinese |  -         |
=> test(design): Add test cases for ConfigProvider prefixCls and iconPrefixCls

packages/charts/src/Pie/__tests__/__snapshots__/donut.test.tsx.snap, packages/charts/src/Pie/__tests__/donut.test.tsx, packages/charts/src/Pie/demo/donut-floor.tsx, packages/charts/src/Pie/index.md, packages/charts/src/Pie/index.tsx
- None
| [Image] | [Image] |
| 🇺🇸 English |  🐞 Fix Donut floor number when calculate total value.         |
| 🇨🇳 Chinese |  🐞 修复环图计算总和时未考虑浮点数精度的问题。         |
=> fix(charts): Donut total should handle floor number correctly

packages/design/src/drawer/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/drawer/__tests__/index.test.tsx, packages/design/src/drawer/demo/footerExtra.tsx, packages/design/src/drawer/index.md, packages/design/src/drawer/index.tsx, packages/design/src/drawer/style/index.ts
- None
| 🇨🇳 Chinese | 🆕 Drawer 新增 `footerExtra` 属性，用于设置抽屉底部的额外内容，仅默认页脚生效。<br /> 📢 Drawer 的 DOM 结构调整，原先 `.ant-drawer-footer-content` 类名改为 `.ant-drawer-footer-container`。          |
=> feat(design): Drawer add footerExtra prop

packages/design/src/modal/demo/max-height.tsx, packages/design/src/modal/index.md, packages/design/src/modal/style/index.ts, packages/design/src/tooltip/demo/mouse-follow.tsx
- None
| 🇨🇳 Chinese | 💄 Modal 去掉最大高度限制，高度超出时内容滚动改由上层控制。          |
=> improve(design): Remove Modal body maxHeight, overflowY and borderRadius style

packages/charts/src/Pie/__tests__/__snapshots__/donut.test.tsx.snap, packages/charts/src/Pie/__tests__/donut.test.tsx, packages/charts/src/Pie/index.tsx
- None
- None
| 🇨🇳 Chinese |  🐞 修复 Pie 环图统计组件标题和内容 `formatter` 不生效的问题。         |
=> fix(charts): Pie donut statistic title and content formatter should work

packages/charts/src/Score/demo/basic.tsx, packages/design/src/table/style/index.ts
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/9e1ed32b-552c-4378-8925-977a2263435e) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/88012501-d8de-4996-9516-2a150e9f77d1) |
| 🇨🇳 Chinese |  🐞 修复 Table 可展开时底部出现重复边框的问题。          |
=> fix(design): Remove duplicate border for expandable table

packages/design/src/card/index.tsx, packages/design/src/card/style/index.ts, packages/design/src/config-provider/__tests__/table.test.tsx, packages/design/src/config-provider/index.md, packages/design/src/table/__tests__/index.test.tsx, packages/design/src/table/demo/row-selection.tsx, packages/design/src/table/demo/with-card.tsx, packages/design/src/table/index.md, packages/design/src/table/index.tsx
- None.
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/3f1897ce-8444-4dfc-9e97-35bc85831452) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/63673477-da2b-42f9-9d42-cc6d79e67ae4) |
| 🇨🇳 Chinese |  💄 优化 Table 在无间距卡片内的展示样式，包括第一列和卡片标题对齐、最后一列和卡片操作区对齐、分页器左右增加间距。         |
=> improve(design): Table new style when Card body padding is 0

packages/design/src/table/demo/virtual.tsx, packages/design/src/table/index.md
- None.
- Add virtual list demo for Table:
=> chore(design): Add virtual list demo for Table

packages/ui/src/Password/index.tsx
| 🇺🇸 English |     fix(ui): Fix the focus jump issue of Password component      |
| 🇨🇳 Chinese |      修复Password 组件 焦点跳动问题     |
=> fix(ui): Fix the focus jump issue of Password component

packages/design/src/table/demo/multiple-nesting-tables.tsx, packages/design/src/table/demo/nesting-tables.tsx, packages/design/src/table/style/index.ts, packages/design/src/theme/compact.ts, packages/design/src/theme/default.ts
- None.
- Design Guide:
- Table cellPaddingBlock change:
- large table: 16px => 12px
- middle table: 12px => 8px
- small table: 8px => 4px
- Table cellPaddingBlock change for `compact` theme:
- large table: 12px => 8px
- middle table: 8px => 4px
- small table: 4px => 0px
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/a13ab025-7c0a-4a05-a1fd-11088f331189) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/5708aa5a-7266-4cc5-8b22-dc5ccc1df653) |
| 🇨🇳 Chinese | 🌈 调整 Table 的 Design Token，缩小其单元格的纵向内间距，以对齐设计规范。         |
=> improve(design): Adjust Table token cellPaddingBlock value

packages/ui/src/FooterToolbar/style/index.ts, packages/ui/src/PageContainer/demo/basic.tsx, packages/ui/src/PageContainer/style/index.ts
- None.
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/9ed22215-67d1-447d-b0d4-3158eb38f469) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/b0b34a08-c6a0-4aff-b6a7-e8d129716e09) |
| 🇨🇳 Chinese |  💄 PageContainer 右上角和页脚操作区适配 Input 组件样式，保证宽高和字体符合设计规范。         |
=> improve(ui): PageContainer extra and footer adapt Input style

packages/design/src/config-provider/__tests__/__snapshots__/prefixCls.tsx.snap, packages/design/src/config-provider/__tests__/__snapshots__/spin.test.tsx.snap, packages/design/src/config-provider/__tests__/__snapshots__/styleProviderProps.test.tsx.snap, packages/design/src/config-provider/index.tsx, packages/design/src/form/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/form/__tests__/index.test.tsx
- None
- None
| 🇨🇳 Chinese |  💄 ConfigProvider 内嵌的 App 组件不再创建 DOM 节点，避免增加一层 DOM 结构影响子元素的样式表现。         |
=> improve(design): div => React.Fragment for ConfigProvider nested App

packages/ui/src/FooterToolbar/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/FooterToolbar/index.tsx, packages/ui/src/PageContainer/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/PageContainer/__tests__/index.test.tsx, packages/ui/src/PageContainer/index.tsx
| 🇨🇳 Chinese | 💄 FooterToolbar 子元素的组件尺寸默认为 `large`、字体大小默认为 `middle`。          |
=> improve(ui): FooterToolbar children use large size and middle font-size

packages/ui/src/PageContainer/demo/with-tabs.tsx, packages/ui/src/PageContainer/index.md, packages/ui/src/PageContainer/style/index.ts
- None.
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/864ddb8e-29a5-4d28-ba24-79c3ca807cf4) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/a92204c7-cb62-4512-bba7-f205a0e3ca0e) |
| 🇨🇳 Chinese | 💄 优化 PageContainer 和 Tabs 组合使用时的间距，以对齐设计规范。          |
=> improve(ui): PageContainer style when first child is Tabs

packages/design/src/table/demo/with-card.tsx
- None.
| 🇺🇸 English |  None         |
=> chore(design): Update Table with-card demo

packages/ui/src/FooterToolbar/style/index.ts, packages/ui/src/PageContainer/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/PageContainer/demo/basic.tsx, packages/ui/src/PageContainer/demo/extra-footer.tsx, packages/ui/src/PageContainer/index.tsx, packages/ui/src/Ranger/index.less
- Fix #432.
- 原先基于 ConfigProvider 修改组件尺寸的影响范围不可控，需要改为原来的样式定制方案，并优化样式以适配更多组件场景。
| 🇨🇳 Chinese | 🐞 修复 PageContainer 页头和页脚操作区外的组件尺寸也被改为 `large` 的问题。           |
=> fix(ui): PageContainer extra and footer large size should work correctly

packages/design/src/card/index.tsx, packages/design/src/config-provider/demo/theme.tsx, packages/design/src/config-provider/index.md, packages/design/src/config-provider/index.tsx, packages/ui/src/PageContainer/demo/complete.tsx
| 🇨🇳 Chinese |  🆕 新增 `injectStaticFunction` 属性，用于配置 `message`、`notification` 和 `Modal` 静态方法是否可以消费全局配置，默认开启。         |
=> feat(design): ConfigProvider add injectStaticFunction prop to controlStaticFunction conflicts

packages/design/src/card/index.md, packages/design/src/table/demo/card-table.tsx, packages/design/src/table/index.md, packages/ui/src/PageContainer/demo/header-less.tsx
- None
| 🇺🇸 English |  None         |
=> improve(design): card-table demo

packages/design/src/theme/default.ts, packages/design/src/theme/style/compact.less, packages/design/src/theme/style/default.less
- None.
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/63254483-de69-4dbb-9636-fb5f7164b63c) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/104d8d08-ad5f-4a64-b756-881279e88491) |
| 🇨🇳 Chinese | 🐞 修复 Table 选中行和 `hover` 行的背景色不一致的问题。          |
=> fix(design): Table selected row and hover row bgColor should be same

packages/design/src/_util/genComponentStyleHook.ts
- Fix #253.
| 🇨🇳 Chinese | 📢 去掉所有组件的重置样式，默认继承父元素样式，便于和其他组件组合使用。          |
=> [Feature Branch] improve(design): Remove resetStyle for all components

.github/dependabot.yml
- None
- None
| 🇨🇳 Chinese | None          |
=> [Feature Branch] chore(deps): target-branch change to feature and ignore ahooks upgrade

.eslintrc.js, packages/design/src/config-provider/DefaultRenderEmpty.tsx, packages/design/src/config-provider/index.md, packages/design/src/config-provider/index.tsx, packages/design/src/empty/demo/config-provider.tsx, packages/design/src/empty/index.md
- Ref: #465 and #466
| 🇨🇳 Chinese | 🆕 通过 ConfigProvider `renderEmpty` 定制全局组件的空状态。          |
=> [Feature Branch] feat(design): Customize ConfigProvider renderEmpty for all components

packages/ui/src/Password/locale/en-US.ts
- Ref: #465
- None
| 🇨🇳 Chinese | 🐞 修复 Password 部分英文文案不正确的问题。          |
=> fix(ui): Password en-US text is not correct

.github/dependabot.yml
- None
- None
| 🇺🇸 English |  None         |
=> chore(dependabot): Specify target-branch, commit-message prefix and labels

.github/workflows/ci.yml, .github/workflows/sync-feature-branch.yml
=> config(workflow): Add sync-feature-branch.yml to auto deploy feature branch

.github/workflows/build.yml, .github/workflows/test.yml
- None
- None
| 🇨🇳 Chinese | None          |
=> improve(workflow): ci split to build and test

.github/workflows/sync-feature-branch.yml
- Fix #501
- https://github.com/oceanbase/oceanbase-design/actions/runs/8232822302/job/22511048865
| 🇨🇳 Chinese | None          |
=> fix(workflow): push force to avoid updates rejected

packages/design/src/result/500.tsx, packages/design/src/result/style/index.ts
- Fix #503
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/0857f38a-7949-4744-8450-f100547f0455) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/9df13da3-bf76-4984-8511-2e6647d95c58) |
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/7fe7ddce-f6a2-489a-ba00-4874d191df9f) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/e85400c5-18bc-41ec-a612-edab47608bd1) |
| 🇺🇸 English |  None         |
=> [Feature Branch] fix(design): Result 500 image and content border-radius

packages/design/src/spin/style/index.ts, packages/design/src/table/style/index.ts
- None.
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/7ae69586-aa46-48c5-856b-3b8d7d9790bb) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/cb4820f2-1fbe-4225-8118-0e8141a1d6e0) |
| 🇨🇳 Chinese | 💄 Table 处于 `loading` 时隐藏空状态。🐞 修复 Table 的 `loading` 动画没有水平和垂直居中的问题。          |
=> [Feature Branch] improve(design): hide Table empty when loading

packages/design/src/empty/index.tsx
- None
- None
| 🇨🇳 Chinese | 🐞 修复 Empty `style` 属性不生效的问题。          |
=> fix(design): Empty style prop should work

.dumirc.ts, packages/design/package.json, packages/design/src/index.ts, packages/design/src/locale/index.ts, packages/design/src/tree-select/__tests__/__snapshots__/placeholder.test.tsx.snap, packages/design/src/tree-select/__tests__/placeholder.test.tsx, packages/design/src/tree-select/demo/basic.tsx, packages/design/src/tree-select/demo/multiple.tsx, packages/design/src/tree-select/index.md, packages/design/src/tree-select/index.ts, packages/design/src/tree-select/index.tsx, packages/design/src/tree-select/style/index.ts, pnpm-lock.yaml
- None
| 🇨🇳 Chinese | - 📢 TreeSelect 默认填充 `placeholder`，并支持通过 ConfigProvider `locale.global.placeholder` 或 `locale.TreeSelect.placeholder` 进行全局配置。- 🆕 ConfigProvider 新增 `locale.TreeSelect.placeholder` 属性，用于配置 Select 的默认 `placeholder`。          |
=> feat(design): TreeSelect add default placeholder and ConfigProvider support to config it global

packages/ui/src/ProTable/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/ProTable/__tests__/index.test.tsx, packages/ui/src/ProTable/index.tsx
- Ref: #549
| 🇨🇳 Chinese |  -         |
=> 🛡 test(ui): Add test cases for ProTable

.dumirc.ts, packages/design/src/cascader/demo/basic.tsx, packages/design/src/cascader/demo/multiple.tsx, packages/design/src/cascader/index.md, packages/design/src/select/demo/multiple.tsx, packages/design/src/select/demo/variant.tsx, packages/design/src/select/index.md, packages/design/src/select/style/index.ts, packages/design/src/tag/style/index.ts, packages/design/src/theme/default.ts, packages/design/src/tree-select/index.tsx, packages/design/src/tree-select/style/index.ts
- None
- Design Guide:
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/7433648a-469c-494d-a297-0345aa7c13ba) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/9ca6a242-d6a6-4f51-a71f-bb2446637651) |
| 🇨🇳 Chinese |  💄 优化 Select、TreeSelect 和 Cascader 多选项的背景色和边框色，以对齐设计规范。        |
=> 💄 improve(style): Multiple item background and border color for Select, TreeSelect and Cascader

packages/design/src/table/index.tsx, packages/ui/src/ProTable/demo/light-filter.tsx, packages/ui/src/ProTable/index.md, packages/ui/src/ProTable/index.tsx, packages/ui/src/ProTable/style/index.ts
- Ref: #554
| 🇨🇳 Chinese | 🐞 修复 LightFilter 定制样式在 ProTable 轻量筛选场景下不生效的问题。          |
=> fix(ui): LightFilter style in ProTable should work

tests/setupTests.ts
https://github.com/oceanbase/oceanbase-design/actions/runs/8663581100/job/24239825077
- Remove vitest mock for react
| 🇨🇳 Chinese |  -         |
=> fix(test): Remove vitest mock for react

.dumirc.ts, packages/design/src/radio/demo/radio-button.tsx, packages/design/src/radio/demo/radio.tsx, packages/design/src/radio/index.md, packages/design/src/theme/default.ts
- None
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/13e008dc-95fd-490a-afe2-33914e73f9a8) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/4c7f9029-bcd1-463e-822a-f30f7ad5d02a) |
| 🇨🇳 Chinese | 💄 优化 Radio.Button 选中置灰态的背景颜色，避免和字体颜色区分不清。          |
=> improve(design): checked and disabled Radio.Button style

packages/design/src/config-provider/__tests__/theme.test.tsx, packages/design/src/config-provider/index.tsx
- None
- None
| 🇨🇳 Chinese | 🐞 修复 ConfigProvider 自定义 `theme.token.fontFamily` 不生效的问题。           |
=> fix(design): ConfigProvider theme.token.fontFamily customization should work

packages/design/src/empty/style/index.ts
- None
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/fba9c95a-e8bc-434c-a061-a21cc798549b) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/92fb3361-efe1-444b-a5bb-d56fa1b06d89) |
| 🇨🇳 Chinese | 💄 优化 Empty 步骤提示的样式，以对齐设计稿。          |
=> improve(design): Empty steps style

.dumirc.ts, packages/design/src/breadcrumb/demo/basic.tsx, packages/design/src/breadcrumb/demo/icon.tsx, packages/design/src/breadcrumb/demo/menu.tsx, packages/design/src/breadcrumb/index.md, packages/design/src/cascader/index.md, packages/design/src/theme/default.ts
- None
- Design Guide:
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/059e7545-de9d-4ce4-ab55-fc710c0d85b7) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/0b5890b4-3dd2-4bdb-af3d-6c268c37e3b9) |
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/274800e5-ba4a-45b3-a07c-d2947b3de423) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/3f59beb7-4bc1-419f-a6a5-f7af6eb45ae7) |
| 🇨🇳 Chinese | 💄 将 Breadcrumb 字体大小改为 12px，以对齐设计规范。          |
=> improve(design): Breadcrumb style

packages/codemod/bin/upgrade-list.json
- None
- The latest version should be `^0.3.0` instead of `^0.2.0`.
| 🇨🇳 Chinese |  [codemod] 🐞 修复自动安装的依赖版本不是最新的问题。         |
=> fix(codemod): ^0.2.0 => ^0.3.0 for upgrade deps list

packages/design/src/descriptions/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/menu/index.ts, packages/design/src/segmented/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/tag/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/tree-select/index.tsx, packages/ui/src/Action/Group.tsx, packages/ui/src/PageContainer/__tests__/__snapshots__/index.test.tsx.snap
- None
- https://github.com/oceanbase/oceanbase-design/actions/runs/9595291933/job/26459695644
- https://github.com/oceanbase/oceanbase-design/actions/runs/9595291928/job/26459695657
=> fix(test): Update snapshots + fix(build): ts error for menu and tree-select

packages/design/src/result/style/index.ts
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/d85e28eb-505e-404c-8542-f15e88d2fd0c) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/71bb6d29-21d2-4968-99bb-ff6b33690c9f) |
| 🇨🇳 Chinese | 💄 优化 Result 样式，包括标题加粗、加大操作区的按钮行高和圆角。          |
=> improve(design): Result title and extra style

packages/design/src/alert/demo/action.tsx, packages/design/src/alert/demo/over-length.tsx, packages/design/src/alert/style/index.ts
- None
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/450d9c8d-52d8-470a-9a16-3f218596bc04) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/ee03dac3-91d3-4f59-be42-ca88e277fddd) |
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/7618bdfe-868e-4b98-9068-9186709f34ae)
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/0ede87eb-231f-4e8a-ba03-5cac36ed93ec) |
| 🇨🇳 Chinese | 💄 优化 Alert 的间距样式，以对齐设计规范。          |
=> improve(design): Alert style to follow design guide

packages/design/src/button/demo/loading.tsx, packages/design/src/select/style/index.ts
- None
| ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/d014f5d9-a1ca-4f00-94e0-05655d157819) | ![image](https://github.com/oceanbase/oceanbase-design/assets/14918822/02d11b64-5b21-462f-b58e-0f4ef20a4825) |
| 🇨🇳 Chinese | 💄 优化 Select 加载器的颜色，使其更具识别度。          |
=> improve(style): Select loading color

packages/ui/src/BasicLayout/locale/en-US.ts, packages/ui/src/BasicLayout/locale/zh-CN.ts, packages/ui/src/BasicLayout/locale/zh-TW.ts
- None
- `蚂蚁集团` => `北京奥星贝斯科技有限公司` for BasicLayout.
| 🇨🇳 Chinese | 📢 BasicLayout 公司名从 `蚂蚁集团` 改为 `北京奥星贝斯科技有限公司`。          |
=> chore(ui): Modify company name for BasicLayout about

.dumirc.ts
- https://clarity.microsoft.com
- None
=> config: Add clarity script for user behavior analytics

.github/workflows/sync-feature-branch.yml
=> [Feature Branch] chore(workflow): GITHUB_TOKEN => SYNC_TOKEN for sync-feature-branch

.dumirc.ts, packages/design/src/switch/demo/basic.tsx, packages/design/src/switch/demo/disabled.tsx, packages/design/src/switch/demo/loading.tsx, packages/design/src/switch/demo/size.tsx, packages/design/src/switch/index.md
=> docs(design): Add docs and demo for Switch

packages/design/src/theme/index.md
- None
- None
| 🇨🇳 Chinese | - 📖 新增阿里云和 less 主题使用文档，优化暗色主题使用文档。          |
=> improve(docs): Update theme usage docs

package.json, packages/design/package.json, packages/design/src/list/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/modal/__tests__/__snapshots__/progress.test.tsx.snap, packages/design/src/table/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/PageContainer/__tests__/__snapshots__/index.test.tsx.snap, pnpm-lock.yaml
- #634
- Cherry pick #634 to fix CI failure.
=> chore(deps): Upgrade antd from 5.18.3 to 5.19.2

packages/design/src/theme/style/aliyun.less, packages/design/src/theme/style/compact.less, packages/design/src/theme/style/dark.less, packages/design/src/theme/style/default.less
=> chore(design): Update theme less variable

packages/design/src/form/demo/form-item-tooltip.tsx, packages/design/src/theme/default.ts, packages/design/src/theme/style/compact.less, packages/design/src/theme/style/dark.less, packages/design/src/theme/style/default.less, packages/design/src/tooltip/MouseTooltip.tsx, packages/design/src/tooltip/demo/mouse-follow.tsx, packages/design/src/tooltip/demo/type.tsx, packages/design/src/tooltip/hooks/useTooltipTypeList.ts, packages/design/src/tooltip/index.md, packages/design/src/tooltip/index.tsx
- None
| ![image](https://github.com/user-attachments/assets/1916a289-529a-4746-8c97-7c36b26c4111) | ![image](https://github.com/user-attachments/assets/330fcf2e-9b9f-4ef1-b3c3-a49d7257a03b)|
| 🇨🇳 Chinese | - ⭐️ Tooltip 默认背景改为白色、默认字体改为黑色，以对齐设计规范。          |
=> [Feature Branch] improve(design): Tooltip background color change to #ffffff

packages/design/src/input/demo/allowClear.tsx, packages/design/src/input/demo/password.tsx, packages/design/src/input/demo/showCount.tsx, packages/design/src/input/index.md
- None
| Password | showCount | allowClear |
| :--- | :--- | :--- |
| ![image](https://github.com/user-attachments/assets/d04bfdde-01e5-4564-9775-27c204b5f64e) | ![image](https://github.com/user-attachments/assets/e7562ca6-4650-4878-9918-d9adeaf44825) | ![image](https://github.com/user-attachments/assets/a59669f9-2507-41d0-8a81-0dd445957962) |
=> chore(design): Add password, showCount and allowClear demo for Input

docs/ui/ui-use-with-vite.md
- Vite + @oceanbase/ui 项目模板: https://stackblitz.com/edit/vite-oceanbase-ui
| 🇨🇳 Chinese | - 📖 新增 @oceanbase/ui 在 Vite 中使用的文档。          |
=> feat(docs): Add @oceanbase/ui and vite docs

.dumi/theme/slots/Content/index.tsx
- #682
| ![image](https://github.com/user-attachments/assets/c5c11a72-9ddb-42a4-b693-3bdd124a1b7a) | ![image](https://github.com/user-attachments/assets/823a4fb2-004c-4fb0-b032-a7f3b8f3a353) |
| ![image](https://github.com/user-attachments/assets/3a52c49b-cc37-4a0d-9f3d-a7998810aeea) | ![image](https://github.com/user-attachments/assets/939b4d57-ab50-4fc5-8f80-332ebbf7b836) |
=> improve(site): Docs max-width 1280px => 1100px

packages/charts/src/index.less, packages/charts/src/index.ts
- None
| 🇨🇳 Chinese | - 🐞 修复 tooltip 无法换行、导致内容溢出的问题。         |
=> fix(charts): Remove tooltip `white-space: nowrap` style

packages/codemod/transforms/__testfixtures__/style-to-token/function.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/function.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/hooks.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/hooks.output.js, packages/codemod/transforms/__tests__/style-to-token.test.ts, packages/codemod/transforms/style-to-token.js
- None
- None
| 🇨🇳 Chinese | 🐞 修复普通函数和匿名函数自动改写成 Design Token 时，应该使用 `token` 对象而不是 `useToken()` 的问题。         |
=> fix(codemod): normal function and anonymous function should use token object

README.md, packages/design/src/typography/index.md
=> fix(docs): typo in README and Typography

.dumi/rehypePlugin.ts, .dumi/theme/builtins/Caution.tsx, .dumi/theme/builtins/Do.tsx, .dumi/theme/builtins/Donot.tsx, .dumi/theme/common/styles/Markdown.tsx, docs/blog/chart-classification-palette-design-guide.md, docs/blog/chart-semantic-palette-design-guide.md, docs/spec/chart-color.md, docs/spec/loading.md, docs/spec/navigation.md, docs/spec/page-container.md, docs/spec/product-graphic.md, docs/spec/product-icon.md, docs/spec/radius.md, docs/spec/shadow.md, docs/spec/system-color.md
=> improve(docs): Style for spec and blog

packages/design/src/select/demo/remote-search.tsx, packages/design/src/select/index.md, packages/design/src/select/index.tsx, packages/design/src/spin/index.md
=> demo(design): Add remote search demo for Select

packages/design/src/select/index.tsx
- Result by #692
- Build log: https://github.com/oceanbase/oceanbase-design/actions/runs/10667032020/job/29563741288
| 🇨🇳 Chinese | -         |
=> fix(design): SelectProps type error

docs/spec/product-graphic.md
=> improve(docs): Style for product graphic

.dumi/theme/SiteThemeProvider.tsx, .dumi/theme/builtins/ColorChunk/index.tsx, .dumi/theme/builtins/TokenTable/index.tsx, .dumi/theme/slots/Header/Logo.tsx, packages/design/src/theme/demo/previewer.less, packages/design/src/theme/index.md
- None
| 🇨🇳 Chinese | - 📖 主题文档新增 Design Token 列表，便于开发侧查阅。          |
=> feat(docs): Add theme token API table

packages/design/src/tag/demo/ellipsis.tsx, packages/design/src/tag/index.tsx, packages/design/src/tag/style/index.ts
1. Icon with ellipsis is abnormal for tag
| ![image](https://github.com/user-attachments/assets/8d93876f-813c-42ca-9252-9bbb3f6f0695)|![image](https://github.com/user-attachments/assets/d8706dc4-e34b-40f5-8a9e-49672ed8342c)|
| 🇺🇸 English |   Typography uses custom Icon in the case of ellipsis        |
| 🇨🇳 Chinese |    Typography 省略情况下使用自定义 Icon       |
=> fix(Tag):   The ellipsis with icons should work

packages/ui/src/Action/Group.tsx, packages/ui/src/Action/Item.tsx, packages/ui/src/Action/demo/button.tsx, packages/ui/src/Action/demo/fixed.tsx, packages/ui/src/Action/demo/groupControl.tsx, packages/ui/src/Action/demo/link.tsx, packages/ui/src/Action/demo/loading.tsx, packages/ui/src/Action/index.md
- None
| middle | small |
| ![image](https://github.com/user-attachments/assets/0efd219d-6f8a-4de1-b465-b9aa70dac8a7) | ![image](https://github.com/user-attachments/assets/ff1b3858-202d-41fa-8af9-b4403c2adfe8) |
| 🇨🇳 Chinese | - 🆕 Action.Group 新增 `buttonSize` 属性，用于设置按钮大小。🆕 Action.Button 新增 `size` 属性，用于设置按钮大小。           |
=> feat(ui): Action.Group add buttonSize prop and Action.Button add size prop

.dumirc.ts, packages/design/src/divider/demo/horizontal.tsx, packages/design/src/divider/demo/vertical.tsx, packages/design/src/divider/index.md, packages/design/src/grid/index.md
- None
| 🇨🇳 Chinese | - 📖 新增 Divider 的示例和文档。         |
=> feat(design): Add Divider docs

.dumirc.ts, packages/design/src/divider/demo/horizontal.tsx, packages/design/src/skeleton/demo/basic.tsx, packages/design/src/skeleton/index.md
- None
| 🇨🇳 Chinese | - 📖 新增 Skeleton 的文档和示例。          |
=> [Feature Branch] feat(design): Add Skeleton docs

packages/codemod/bin/upgrade-list.json
- None
- None
| 🇨🇳 Chinese | - ⭐️ 自动化升级的目标版本更新为 `^0.4.0`。          |
=> [Feature Branch] chore(codemod): Upgrade version to ^0.4.0

docs/design/design-use-with-nextjs.md
- Nextjs + @oceanbase/design 项目模板: https://stackblitz.com/edit/nextjs-oceanbase-design
| 🇨🇳 Chinese | - 📖 新增 @oceanbase/design 在 Nextjs 中的 [使用文档](https://design.oceanbase.com/docs/design-use-with-nextjs) 和 [项目模板](https://stackblitz.com/edit/nextjs-oceanbase-design)。          |
=> [Feature Branch] feat(docs): Add @oceanbase/design and nextjs docs

packages/design/src/theme/default.ts
- None
| ![image](https://github.com/user-attachments/assets/28703c72-6232-4065-995a-1ee514f85e77) | ![image](https://github.com/user-attachments/assets/af572a0c-ead7-4f76-9471-0e2e0a5f9c86) |
| 🇨🇳 Chinese | - 💄 修改 Tag 的默认字体颜色为 `#5c6b8a`，以对齐设计规范。          |
=> [Feature Branch] improve(design): Tag defaultColor change to #5c6b8a

packages/ui/src/ProTable/style/index.ts
- None
| ![image](https://github.com/user-attachments/assets/c8b9ea33-fedf-4cd9-8335-d3fd57c9f70a) | ![image](https://github.com/user-attachments/assets/07340fda-108d-4bfd-899f-54d21916b921) |
| ![image](https://github.com/user-attachments/assets/16dfab18-2523-4d7d-9031-8c6bb0f66ec5) | ![image](https://github.com/user-attachments/assets/b59ca3ab-7924-4698-be50-d3421fa6cdff) |
| 🇨🇳 Chinese | - 💄 优化 ProTable 查询表单样式，将搜索&重置按钮组和展开收起互换位置。          |
=> improve(ui): reverse position for button group and expand element in ProTable query form

.dumirc.ts, packages/design/src/button/demo/dropdown.tsx, packages/design/src/button/style/index.ts, packages/design/src/dropdown/demo/basic.tsx, packages/design/src/dropdown/demo/dropdown-button.tsx, packages/design/src/dropdown/index.md
- None
| ![image](https://github.com/user-attachments/assets/9632d61e-110e-4fa7-85cc-a3ea22b56380) | ![image](https://github.com/user-attachments/assets/6be4e468-1103-4b99-bd9e-545fe236bbaa) |
| 🇨🇳 Chinese | - 🐞 修复 Dropdown.Button 为主按钮时分割线超出和背景色不正确的问题。- 📖 新增 Dropdown 的文档和示例。|
=> improve(design): primary Dropdown.Button divider and background style

packages/design/src/index.ts, packages/design/src/radio/demo/over-length.tsx, packages/design/src/radio/index.md, packages/design/src/radio/index.ts, packages/design/src/radio/index.tsx, packages/design/src/radio/style/index.ts
| ![image](https://github.com/user-attachments/assets/a9abac16-8198-4a46-88b5-06a3de40f5c1) | ![image](https://github.com/user-attachments/assets/0e43192c-5bfa-4aeb-9fc3-42702d0247ca) |
| 🇨🇳 Chinese | - 💄 优化 Radio 超长内容的垂直对齐样式，从居中对齐改为顶部对齐。         |
=> improve(design): vertical align center => baseline for over length Radio

.dumirc.ts, packages/design/src/checkbox/demo/basic.tsx, packages/design/src/checkbox/demo/group.tsx, packages/design/src/checkbox/demo/over-length.tsx, packages/design/src/checkbox/index.md, packages/design/src/checkbox/index.ts, packages/design/src/checkbox/index.tsx, packages/design/src/checkbox/interface.ts, packages/design/src/checkbox/style/index.ts, packages/design/src/index.ts
| ![image](https://github.com/user-attachments/assets/f5ec5953-7cbf-46f0-8abf-c32d0f12370b) | ![image](https://github.com/user-attachments/assets/e789c9a7-a3d6-41d3-b855-13ef813abee6) |
| 🇨🇳 Chinese | - 💄 优化 Checkbox 超长内容的垂直对齐样式，从居中对齐改为顶部对齐。         |
=> improve(design): vertical align center => baseline for over length Checkbox

packages/ui/src/PageContainer/style/index.ts
| ![image](https://github.com/user-attachments/assets/8bd0e6bc-efc8-40c9-95f1-eee03d06d2cf) | ![image](https://github.com/user-attachments/assets/d280f21a-1593-4418-bf91-b67a1906b28e) |
| 🇨🇳 Chinese |  - 💄 去掉 PageContainer 页头的上内间距，让页面布局更加紧凑。         |
=> improve(ui): Remove PageContainer header paddingBlockStart

packages/design/src/card/style/index.ts
| ![image](https://github.com/user-attachments/assets/a35cccf5-2442-4a20-b384-a17483e9b519) | ![image](https://github.com/user-attachments/assets/ec660093-99cd-40c5-a1c5-c0e9e3e77b10) |
| 🇨🇳 Chinese | - 💄 优化 Card 无分割线时的底部间距。         |
=> improve(design): Card body padding-bottom without divider

packages/ui/src/Password/Content.tsx, packages/ui/src/Password/index.tsx, packages/ui/src/Password/locale/en-US.ts, packages/ui/src/Password/locale/zh-CN.ts, packages/ui/src/Password/locale/zh-TW.ts
| ![image](https://github.com/user-attachments/assets/1364ba07-2797-4acf-a397-a22a4c61808c) | ![image](https://github.com/user-attachments/assets/9d5fb67c-a118-494b-b041-dcec8634b07b) |
| ![image](https://github.com/user-attachments/assets/d11547bb-6738-4b2b-8a15-e18df56bc7fc) | ![image](https://github.com/user-attachments/assets/28f09cd8-3032-4f0b-acab-12dfceb1d47d) |
| ![image](https://github.com/user-attachments/assets/b7fcbf56-96c4-46ca-ab9f-034e5852a0f9) | ![image](https://github.com/user-attachments/assets/6a80dbcb-2d89-427a-b9c6-ad45babc59fa) |
| 🇨🇳 Chinese |  - 💄 优化 Password 的多处样式，以对齐设计规范。         |
=> improve(ui): Password style

packages/design/src/card/style/index.ts, packages/design/src/switch/demo/size.tsx
| ![image](https://github.com/user-attachments/assets/183e9c47-2afa-496f-afa1-c295d2fd28a3) | ![image](https://github.com/user-attachments/assets/c7f4d754-d27b-4f4e-89df-e4fbaae9d3c7) |
| 🇨🇳 Chinese | - 💄 优化小尺寸 Card 带页签时的头部间距样式。         |
=> improve(design): small Card head padding-top with tabs set to 8px

packages/design/src/table/index.tsx, packages/design/src/table/style/index.ts
| ![image](https://github.com/user-attachments/assets/e3165c55-c2a4-464e-84ec-3aaa71addb3e) | ![image](https://github.com/user-attachments/assets/827904b2-1ed9-4ab3-8615-57c94cccee31) |
| 🇨🇳 Chinese | - 💄 优化 Table 底部分割线的展示逻辑，无分页器时也应该展示。         |
=> improve(design): Table border-bottom display logic

packages/design/src/table/style/index.ts
- Fix #822
| ![image](https://github.com/user-attachments/assets/5a137854-8013-428c-9f47-2d425ae12eee) | ![image](https://github.com/user-attachments/assets/53d963be-1e1c-4115-8e3a-09d806c0cda6) |
=> fix(design): Table border-radius should be 0 in some cases

packages/design/src/table/__tests__/index.test.tsx, packages/design/src/table/index.md, packages/ui/src/ProTable/__tests__/index.test.tsx, packages/ui/src/ProTable/demo/empty.tsx, packages/ui/src/ProTable/demo/expandable.tsx, packages/ui/src/ProTable/index.md, packages/ui/src/ProTable/index.tsx
| ![image](https://github.com/user-attachments/assets/f62a1ee7-67c7-4991-87ed-615f29bdad3b) | ![image](https://github.com/user-attachments/assets/ae1095c7-c957-41eb-a30d-9db30970b657) |
| ![image](https://github.com/user-attachments/assets/dc790ff0-1e07-489b-9f90-e3ce2c619709) | ![image](https://github.com/user-attachments/assets/ec382aee-31be-4708-9b0e-513bc8b31149) |
| 🇨🇳 Chinese | - 💄 ProTable 对齐 Table 的可展开、空状态和 `footer` 样式。          |
=> improve(ui): ProTable expandable, empty and footer style follow Table

packages/design/src/slider/style/index.ts
- #815
| 🇨🇳 Chinese | - 🐞 修复 Slider 两端标签的对齐样式在部分场景下不生效的问题。         |
=> fix(design): Slider start and end mark should align always

packages/design/src/typography/hooks/useClassName.ts, packages/design/src/typography/style/index.ts
=> fix(design): Typographt.Text editable and edit style should be correct

packages/design/src/theme/default.ts
- None
| ![image](https://github.com/user-attachments/assets/6e60eca5-1bfa-44e5-9a79-ee4871436075) | ![image](https://github.com/user-attachments/assets/1e4e9fd8-6d2e-4d47-8b9b-e1c7958d3eea) |
| 🇨🇳 Chinese | - 🌈 将 Design Token `lineWidthFocus` 设为 0，以去掉组件聚焦时的线条样式。         |
=> improve(design): lineWidthFocus token => 0 to remove focus outline

packages/design/src/result/demo/over-length.tsx, packages/design/src/result/index.md, packages/design/src/result/style/index.ts
| ![image](https://github.com/user-attachments/assets/41424bb2-2193-476f-9a49-c895ce3734a0) | ![image](https://github.com/user-attachments/assets/42dfd1cd-3b45-45bb-b38f-3c233ffaf45e) |
| 🇨🇳 Chinese | - 💄 优化 Result 超长内容的样式，限制副标题的最大宽度为 600px、内容区的最大宽度为 1000px。         |
=> improve(style): Result subTitle max-width => 600px for over length style

packages/design/src/reset.css
- None
| ![image](https://github.com/user-attachments/assets/a7552afe-5608-43d2-8b1e-69a41f19c7f6) | ![image](https://github.com/user-attachments/assets/c71bdb73-182e-4644-a815-002080929e61) |
| ![image](https://github.com/user-attachments/assets/24d25267-1c76-462e-a062-ea8593e1284e) | ![image](https://github.com/user-attachments/assets/3334de94-5ea0-4c1c-9d76-ae13d76ef075) |
| ![image](https://github.com/user-attachments/assets/f1f17cda-420c-4f65-9e4c-3f0e4afaeb29) | ![image](https://github.com/user-attachments/assets/c44df21a-f1ba-4650-9d1f-6f7964031ea2) |
| 🇨🇳 Chinese | - 💄 将全局的滚动条颜色改为 `#e2e8f3`。          |
⚠️ Please check all items below before requesting a reviewing. …
=> improve(design): scrollbar color

packages/design/src/tooltip/style/index.ts
- None
| ![image](https://github.com/user-attachments/assets/284a7a58-6ce9-45a6-9dbd-c8106bdbbbf6) | ![image](https://github.com/user-attachments/assets/65bf919f-ffdd-4724-8883-b3b845fb02b9) |
| 🇨🇳 Chinese | - 💄 优化 Tooltip 可关闭图标的颜色样式。          |
=> improve(design): Tooltip closeIcon color

.dumirc.ts, packages/design/src/popover/demo/basic.tsx, packages/design/src/popover/demo/over-length.tsx, packages/design/src/popover/demo/trigger.tsx, packages/design/src/popover/demo/with-table.tsx, packages/design/src/popover/index.md, packages/design/src/tooltip/demo/over-length.tsx, packages/design/src/tooltip/index.md
- None
| 🇨🇳 Chinese | - 📖 新增 Popover 的文档和示例。          |
=> feat(design): Add Popover docs and demos

README.md
- None
- None
| 🇨🇳 Chinese |  -         |
=> chore(README): Add contributors image

packages/design/src/table/style/index.ts
- Ref: #846
| ![image](https://github.com/user-attachments/assets/feab321d-034c-4f95-a04a-772ce1e9a4b6) | ![image](https://github.com/user-attachments/assets/e9d76a1b-ab26-4b5b-b67a-763af8f7911d) |
| 🇨🇳 Chinese | - 💄 将 Table 虚拟滚动条的颜色改为 `#e2e8f3`，和全局滚动条保持一致。          |
=> improve(design): Table virtual scrollbar color

packages/design/src/card/index.tsx, packages/design/src/table/demo/card-table.tsx, packages/design/src/table/demo/dynamic-settings.tsx, packages/design/src/table/index.tsx, packages/design/src/table/style/index.ts, packages/ui/src/ProTable/index.tsx
- None
| Guide | Achievement |
| ![image](https://github.com/user-attachments/assets/c9527481-edf5-4f9f-8b10-f2dce032d823) | ![image](https://github.com/user-attachments/assets/667c6414-112e-4c99-8740-2b9f4bfc3b63) |
| ![image](https://github.com/user-attachments/assets/bfdf259a-d05f-4e60-a254-ba240b74fcf3) | ![image](https://github.com/user-attachments/assets/2c711298-9301-4ef4-9418-4e8e736ab946) |
| 🇨🇳 Chinese | - 优化 Table 嵌套子表格和可展开内容的样式，以对齐最新的设计规范。         |
=> improve(design): Table expandable style

packages/design/src/table/style/index.ts
- Fix #865
| ![image](https://github.com/user-attachments/assets/3ce5fd0d-095d-49ef-833a-71e31df5185f) | ![image](https://github.com/user-attachments/assets/666b3312-97af-47a8-a2b3-dd5f4efea6da) |
| 🇨🇳 Chinese |  - 🐞 修复普通 Table 的单元格出现底部边框的问题。        |
=> fix(design): should remove cell border for normal Table

packages/design/src/table/demo/bordered.tsx, packages/design/src/table/style/index.ts
- None
| ![image](https://github.com/user-attachments/assets/f834d3c9-2285-4715-a1da-e3d9238b554a) | ![image](https://github.com/user-attachments/assets/d10d557c-181e-41f8-b1b7-592a96861c71) |
| ![image](https://github.com/user-attachments/assets/07dae480-27c5-4e3c-b0b7-9601f66b5032) | ![image](https://github.com/user-attachments/assets/f38c0250-443d-482e-8220-0600645619c3) |
| 🇨🇳 Chinese | - 💄 优化 Table 带边框时的底部圆角样式。          |
=> improve(design): Table bordered style

packages/design/src/_util/genStyle.ts, packages/ui/src/PageContainer/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/PageContainer/demo/extra-footer.tsx
- None
| ![image](https://github.com/user-attachments/assets/a3c202e4-8cc8-4a2c-866e-1aacb3ceb06d) | ![image](https://github.com/user-attachments/assets/fbeac4c1-a22d-47a0-bdee-79aebd79ef59) |
| 🇨🇳 Chinese | - 🐞 修复 PageContainer 右上角操作区 Select 多选框没有垂直居中的问题。          |
=> fix(ui): multiple Select should vertical align in PageContainer extra

.dumirc.ts, packages/design/src/collapse/demo/accordion.tsx, packages/design/src/collapse/demo/basic.tsx, packages/design/src/collapse/demo/borderless.tsx, packages/design/src/collapse/demo/custom.tsx, packages/design/src/collapse/demo/expand-icon-position.tsx, packages/design/src/collapse/demo/ghost.tsx, packages/design/src/collapse/index.md, packages/design/src/config-provider/index.tsx, packages/design/src/theme/default.ts
- None
| 🇨🇳 Chinese | - 📖 新增 Collapse 的文档和示例。- 💄 将 Collapse 默认展开图标改为实心箭头。- 💄 弱化 Collapse 边框，将边框颜色改为 `#E2E8F3`。           |
=> feat(design): New Collapse

packages/design/src/card/demo/grid.tsx, packages/ui/src/DateRanger/index.less
- None
- None
| 🇨🇳 Chinese | - 💄 优化 DateRanger 的鼠标样式。          |
=> improve(ui): cusor style for DateRanger

packages/charts/package.json, packages/design/package.json, packages/icons/package.json, packages/ui/package.json, packages/util/package.json
- None
- None
| 🇨🇳 Chinese | - ⚡ 设置 @oceanbase/design、@oceanbase/ui、@oceanbase/charts、@oceanbase/icons 和 @oceanbase/utils 的 `sideEffects`，以支持 tree shaking。          |
=> optimize(build): Add sideEffects for tree shaking

.dumi/theme/builtins/DemoWrapper/index.tsx, packages/charts/src/Pie/index.md, packages/design/src/card/index.md, packages/design/src/empty/index.md, packages/design/src/form/index.md, packages/design/src/typography/index.md, packages/ui/src/PageContainer/index.md
- None
| ![image](https://github.com/user-attachments/assets/9678453d-58d3-4e95-99c9-e363570085a3) | ![image](https://github.com/user-attachments/assets/1b2ac373-da7e-49d1-8c04-334fe65f849a) |
| 🇨🇳 Chinese | - 📖 修复 demo 展开全部代码不生效的问题。- 📖 修复部分组件不展示 demo 操作栏的问题。          |
=> fix(site): show code and debug for demo should work

packages/ui/src/Action/Group.tsx, packages/ui/src/ContentWithQuestion/style/index.ts
- Fix #887
- Fix #874
- Fix #887
=> fix(ci): ContentWithQuestion and Action ts error

docs/design/design-CHANGELOG.md, docs/ui/ui-CHANGELOG.md
`2024-12-14`
- 📖 修复 demo 展开全部代码不生效的问题。[#888](https://github.com/oceanbase/oceanbase-design/pull/888)
- 📖 修复部分组件不展示 demo 操作栏的问题。[#888](https://github.com/oceanbase/oceanbase-design/pull/888)
- ⚡ 设置 `sideEffects`，以支持 tree shaking。[#886](https://github.com/oceanbase/oceanbase-design/pull/886)
- Collapse [#882](https://github.com/oceanbase/oceanbase-design/pull/882)
- 📖 新增 Collapse 的文档和示例。
- 💄 将 Collapse 默认展开图标改为实心箭头。
- 💄 弱化 Collapse 边框，将边框颜色改为 `#E2E8F3`。
- Table
- 🐞 修复普通 Table 的单元格出现底部边框的问题。[#879](https://github.com/oceanbase/oceanbase-design/pull/879)
- 💄 优化 Table 带边框时的底部圆角样式。[#880](https://github.com/oceanbase/oceanbase-design/pull/880)
- 💄 优化 Table 空状态在 Popover、Tooltip 下的高度。[#891](https://github.com/oceanbase/oceanbase-design/pull/891)
---
`2024-12-14`
- ⚡ 设置 `sideEffects`，以支持 tree …
=> chore(docs): Add changelog for @oceanbase/design@0.4.3 and @oceanbase/ui@0.4.4

.github/workflows/preview-build.yml, .github/workflows/preview-deploy.yml
=> fix(workflow): Remove pr-id.text in preview to avoid security problem

packages/design/src/table/style/index.ts
- #865
| ![image](https://github.com/user-attachments/assets/ec54e07b-3c4d-42ec-96b7-d1f0d07500ac) | ![image](https://github.com/user-attachments/assets/4929f9c8-0b76-4223-a1dc-70ea0d2d9242) |
| ![image](https://github.com/user-attachments/assets/2caf65b0-1522-4fce-851e-ae506ec85994) | ![image](https://github.com/user-attachments/assets/6b2a5773-5380-4e90-9c7a-8ef38fbaba9c) |
| 🇨🇳 Chinese | - 🐞 修复 Table 底部圆角和列左侧内间距不正确的问题。          |
=> fix(design): Table border-radius and column padding-left style

.dumirc.ts, packages/design/src/card/index.tsx, packages/design/src/card/style/index.ts, packages/design/src/table/demo/pro-card-table.tsx, packages/design/src/table/index.md, packages/ui/src/ProCard/demo/basic.tsx, packages/ui/src/ProCard/index.md, packages/ui/src/ProCard/index.tsx, packages/ui/src/ProCard/style/index.ts, packages/ui/src/_util/genComponentStyleHook.ts, packages/ui/src/index.ts
- Ref: #422
| ![image](https://github.com/user-attachments/assets/483b7e74-5ee7-4b3b-af99-03820bd07ca2) | ![image](https://github.com/user-attachments/assets/740c050b-22e0-4798-a71c-184f6c2e5c8c) |
| 🇨🇳 Chinese | - 💄 优化 Table 在无间距 ProCard 内的样式，包括第一列和卡片标题对齐、最后一列和卡片操作区对齐、分页器左右增加间距。- 💄 📖 新增 ProCard 的文档和示例。- 💄 优化 ProCard 在无间距时的头部样式。          |
=> improve(design): Table padding when ProCard bodyStyle.padding is 0

packages/design/src/table/style/index.ts
- None
| ![image](https://github.com/user-attachments/assets/f8743b6b-2758-426b-a770-9f860a2d245b) | ![image](https://github.com/user-attachments/assets/4cc39314-f29e-4efc-9a42-fadf262a4366) |
| ![image](https://github.com/user-attachments/assets/45549842-7ad5-45ce-b53d-c779eba8d70c) | ![image](https://github.com/user-attachments/assets/8a6687b4-2369-41a7-b950-a2891a329f15) |
| 🇨🇳 Chinese | - 🐞 修复中小尺寸的可展开 Table 单元格高度不正确的问题。          |
=> fix(design): middle and small expandable Table cell height should be correct

packages/ui/src/Action/Group.tsx, packages/ui/src/Action/demo/button.tsx, packages/ui/src/Action/demo/fixed.tsx, packages/ui/src/Action/demo/groupControl.tsx, packages/ui/src/Action/demo/link.tsx, packages/ui/src/Action/demo/more-text.tsx, packages/ui/src/Action/demo/with-tooltip-popconfirm.tsx, packages/ui/src/Action/index.md
- None
| ![image](https://github.com/user-attachments/assets/86f0ad9c-98fa-4412-8d25-511913ff3956) | ![image](https://github.com/user-attachments/assets/862933de-b25b-447b-a102-569b3a438b03) |
| 🇨🇳 Chinese | - 💄 Action.Link 之间的间隔改为 16px。          |
=> improve(ui): Action.Link gap 8px => 16px

packages/ui/src/Action/Group.tsx
- None
| ![image](https://github.com/user-attachments/assets/263144be-0a06-4d9e-8b5c-d8e36e6112dd) | ![image](https://github.com/user-attachments/assets/ffd8eae3-6d3b-446a-b9c2-2f8edd71f9be) |
| ![image](https://github.com/user-attachments/assets/9019e7cc-7532-448a-a8a2-f2b82af79cf3) | ![image](https://github.com/user-attachments/assets/e4952b2f-8123-458f-bf7e-b2536a45df16) |
| 🇨🇳 Chinese | - 💄 优化 Action 更多按钮的宽度，并去掉下拉菜单的最小宽度。          |
=> improve(ui): Action ellipsis button width and dropdown menu minWidth

packages/design/src/tabs/style/index.ts
- None
| ![image](https://github.com/user-attachments/assets/e751c64f-fe8a-40f6-9830-7d3ab392644b) | ![image](https://github.com/user-attachments/assets/418bdb62-1820-4d37-8349-927c617421eb) |
| ![image](https://github.com/user-attachments/assets/d7df9528-a2d4-46a3-88dd-88a312c53b1a) | ![image](https://github.com/user-attachments/assets/543a4daf-86aa-41e1-83aa-968c4000c49a) |
| 🇨🇳 Chinese | - 💄 优化 Tabs `large` 和 `small` 尺寸的上下间距。          |
=> improve(design): large and small Tabs tab padding

packages/design/src/card/index.tsx, packages/design/src/card/style/index.ts, packages/design/src/table/demo/card-table.tsx, packages/design/src/table/demo/pro-card-table.tsx, packages/design/src/table/style/index.ts, packages/ui/src/ProCard/index.tsx
- None
|   | Before | After |
| :--- | :--- | :--- |
| Card | ![image](https://github.com/user-attachments/assets/18d1ebbf-2003-4dbd-b1bd-82d684d1dd15) | ![image](https://github.com/user-attachments/assets/8e1843ac-4344-4afb-8b85-25f213551ee8) |
| ProCard | ![image](https://github.com/user-attachments/assets/2eaf2d1a-e358-4cc1-b533-384584ee59fb) | ![image](https://github.com/user-attachments/assets/9ee8ff24-9742-451f-b377-5f816263617d) |
| 🇨🇳 Chinese | - 💄 优化 Table 在无分割线 Card 和 ProCard 内的间距。          |
=> improve(design): Table margin in Card and ProCard without divider

packages/ui/src/DateRanger/demo/simple-mode.tsx, packages/ui/src/DateRanger/index.less, packages/ui/src/DateRanger/index.md
- None
| ![image](https://github.com/user-attachments/assets/d5b1401c-156c-4b74-88a0-8eb24c9ee30d) | ![image](https://github.com/user-attachments/assets/93f664bf-bf71-45af-83ef-7aa401f639dc) |
| 🇨🇳 Chinese | - 💄 去掉 DateRanger `focus` 时的阴影样式。          |
=> improve(ui): Remove DateRanger picker box-shadow when focus

packages/design/src/card/style/index.ts, packages/design/src/table/demo/pro-card-table.tsx, packages/design/src/table/style/index.ts, packages/design/src/tabs/index.tsx, packages/design/src/tabs/style/index.ts, packages/design/src/tag/style/index.ts, packages/ui/src/ProCard/demo/basic.tsx, packages/ui/src/ProCard/index.md, packages/ui/src/ProCard/index.tsx, packages/ui/src/ProCard/style/index.ts, packages/ui/src/TagSelect/style/index.ts
| ![image](https://github.com/user-attachments/assets/155305f8-71fc-4d23-bb66-07398249948e) | ![image](https://github.com/user-attachments/assets/2659838f-5358-42d4-b445-5989fee5a0d0) |
| 🇨🇳 Chinese | - 💄 优化 ProCard 页标签样式，以与 Card 页标签样式保持一致。          |
=> improve(ui): ProCard tabs follow Card tabs style

docs/design/design-CHANGELOG.md, packages/design/src/table/demo/card-table.tsx, packages/design/src/table/demo/pro-card-table.tsx, packages/design/src/table/style/index.ts
- None
| ![image](https://github.com/user-attachments/assets/3e223763-1743-44da-8faa-d0e853e43194) | ![image](https://github.com/user-attachments/assets/2c0e93b2-92fc-4e0e-a0de-8231022e2f21) |
| 🇨🇳 Chinese | - 🐞 修复 Table 顶部圆角的样式问题。         |
=> fix(design): Table border-radius top style

docs/design/design-CHANGELOG.md, docs/ui/ui-CHANGELOG.md
`2025-01-15`
- 🌈 自定义 Tabs `horizontalItemGutter` token 值，全局设置页标签间隙。[#935](https://github.com/oceanbase/oceanbase-design/pull/935)
- 🆕 ConfigProvider 新增 `card.divided` 属性，用于配置 Card 是否展示分割线。[#939](https://github.com/oceanbase/oceanbase-design/pull/939)
- Table
- 🐞 修复中小尺寸的可展开 Table 单元格高度不正确的问题。[#924](https://github.com/oceanbase/oceanbase-design/pull/924)
- 💄 Table 点击行可展开时，设置行样式为 `cursor: pointer`。[#925](https://github.com/oceanbase/oceanbase-design/pull/925)
- 💄 优化 Table 在无分割线 Card 和 ProCard 内的间距。[#933](https://github.com/oceanbase/oceanbase-design/pull/933)
- 💄 优化 Table 在无间距 ProCard 内的样式，包括第一列和卡片标题对齐、最后一列和卡片操作区对齐、分页器左右增加间距。[#923](https://github.com/oceanbase/oceanbase-design/pull/923)
- 💄 优化 Table 顶部圆角的样式。[#941](https://github.com/oceanbase/oceanbase-design/pull/941)
---
`2025-01-15`
- …
=> chore(docs): Add changelog for @oceanbase/design@0.4.6 and @oceanbase/ui@0.4.7

packages/codemod/transforms/utils/token.js
- None
- None
| 🇨🇳 Chinese | - ⭐️ 支持颜色值 `rgb(240,242,245)` 到 colorBgLayout 的自动改写。          |
=> enhance(codemod): rgb(240,242,245) => colorBgLayout token

.dumi/theme/common/styles/Markdown.tsx, packages/ui/src/ProTable/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/ProTable/index.tsx, packages/ui/src/ProTable/style/index.ts
- None
| ![image](https://github.com/user-attachments/assets/ecbdb677-a38c-4956-9adf-fdbe9f8c3f02) | ![image](https://github.com/user-attachments/assets/07d9579c-a066-45d9-85d6-01dc2d17466e) |
| ![image](https://github.com/user-attachments/assets/b5d87bfd-9499-449f-8230-9934f9ead833) | ![image](https://github.com/user-attachments/assets/f9ac55cb-996f-4c93-94de-0b9cfdae7031) |
| 🇨🇳 Chinese | - 💄 优化 ProTable 间距，以对齐 Table 在 Card 中的样式。          |
=> improve(ui): ProTable follow Table style in no padding Card

.dumi/hooks/useMenu.tsx, .dumi/pages/index/components/Banner.tsx, .dumi/pages/index/components/util.ts, .dumi/theme/builtins/IconSearch/index.tsx, .dumi/theme/common/PrevAndNext.tsx, .dumi/theme/common/styles/Responsive.tsx, .dumi/theme/slots/Content/index.tsx, .dumi/theme/slots/Header/index.tsx, .dumi/theme/slots/Sidebar/index.tsx, packages/design/src/button/demo/icon.tsx, packages/design/src/menu/interface.ts, packages/design/src/typography/demo/inner.tsx
- None
| Mobile Docs | Mobile Menu |
| ![image](https://github.com/user-attachments/assets/86027398-b189-4a4d-8a75-9ba5fcdbdb37) | ![image](https://github.com/user-attachments/assets/5910b242-ef17-405e-85ce-e52fdfbc9de5) |
| 🇨🇳 Chinese | - 📖 优化官网在移动端的样式和访问体验。          |
=> improve(site): Mobile style

packages/ui/src/DateRanger/PickerPanel.tsx
| 🇨🇳 Chinese | ⭐️ DateRanger 支持自动校验和交换起止时间。       |
=> improve(DateRanger): Should start time is before the end time.

packages/ui/src/ProCard/demo/collapsible.tsx, packages/ui/src/ProCard/demo/ghost.tsx, packages/ui/src/ProCard/index.md, packages/ui/src/ProCard/index.tsx, packages/ui/src/ProCard/style/index.ts, packages/ui/src/ProTable/index.md
- None
| ![image](https://github.com/user-attachments/assets/16b0b7e3-c16a-4d9b-9677-a459de43b826) | ![image](https://github.com/user-attachments/assets/1c8bcbe9-ed02-48f3-831b-13999b9fc578) |
| 🇨🇳 Chinese | - 🐞 修复 ProCard `ghost` 模式下卡片阴影和内容区 padding 不正确的问题。          |
=> fix(ui): ghost ProCard box-shadow and padding style

packages/design/src/tooltip/MouseTooltip.tsx
- None
| 🇨🇳 Chinese | - 🔨 去掉 Tooltip `mouseFollow` 模式下控制台出现的 NaN 告警。          |
=> improve(design): Remove mouseFollow Tooltip console NaN warning

packages/ui/src/DateRanger/Ranger.tsx
特殊场景自动调整的面板弹出位置不符预期，期望可以外部控制时间选择面板弹出位置。
| 🇨🇳 Chinese | - 🆕 DateRanger 透出 `autoAdjustOverflow` 属性，用于控制弹出面板是否自动调整位置。         |
=> feat(ui): DateRanger expose autoAdjustOverflow prop

.npmrc, packages/design/package.json, packages/design/src/tooltip/MouseTooltip.tsx, packages/design/src/tooltip/ReactStickyMouseTooltip.tsx, pnpm-lock.yaml
- None
| 🇨🇳 Chinese | - 🔨 将 [react-sticky-mouse-tooltip](https://github.com/marlo22/react-sticky-mouse-tooltip) 代码内置到 Tooltip，避免控制台告警和错误都指向 `MouseTooltip.jsx`、干扰问题排查。          |
=> improve(design): Built in react-sticky-mouse-tooltip to avoid warning and error point to it

packages/design/package.json, pnpm-lock.yaml
- None
- From `codesandbox`:
| 🇨🇳 Chinese | - 🐞 修复 `@ctrl/tinycolor` 依赖缺失的问题。          |
=> fix(design): Add missing deps @ctrl/tinycolor

packages/design/src/config-provider/index.md, packages/design/src/config-provider/index.tsx
- None
| 🇨🇳 Chinese | - ⭐️ ConfigProvider 移除 `injectStaticFunction` 属性，改为自动判断是否注入可消费全局配置的静态方法。          |
=> fix(design): inject static function to outermost ConfigProvider only

packages/design/src/table/demo/dynamic-settings.tsx, packages/design/src/table/index.tsx, packages/design/src/table/style/index.ts, packages/ui/src/ProTable/index.tsx
| ![image](https://github.com/user-attachments/assets/1188a507-0faa-4ea1-bafa-9c4681cc0838) | ![image](https://github.com/user-attachments/assets/c2aeb7ae-fa8b-445d-8029-63d7e4f49e1d) |
| 🇨🇳 Chinese | - 🐞 修复 Table 可展开&固定列时的间距问题。          |
=> fix(design): expandable and fixed columns Table style

packages/design/src/table/style/index.ts
- None
- Scroll or fixed columns table has extra row and reverses `odd row` and `even row` compared normal table.
| ![image](https://github.com/user-attachments/assets/b4189533-8138-4750-87f2-628f0ea345c8) | ![image](https://github.com/user-attachments/assets/ea817d07-6e4a-4c04-a966-6291b07c4d4e) |
| 🇨🇳 Chinese |  - 🐞 修复 Table 可展开&可滚动时不应该展示斑马条的问题。         |
=> fix(design): expandable and scroll Table should not be zebra style

packages/design/src/dropdown/demo/dropdown-button.tsx, packages/design/src/dropdown/demo/dropdown-with-button.tsx, packages/design/src/dropdown/dropdown-button.tsx, packages/design/src/dropdown/index.md, packages/design/src/dropdown/index.ts, packages/design/src/dropdown/index.tsx, packages/design/src/index.ts
| ![image](https://github.com/user-attachments/assets/2e283794-7798-40ea-a4e5-e10b21814d32) | ![image](https://github.com/user-attachments/assets/d0f838eb-2ad3-4840-ba4d-25aa0f60c0f7) |
| 🇨🇳 Chinese | - 💄 Dropdown.Button 默认图标改为 `DownOutlined` 向下箭头。         |
=> improve(design): Dropdown.Button default icon change to DownOutlined

packages/design/src/typography/demo/copyable.tsx, packages/design/src/typography/demo/editable-modal.tsx, packages/design/src/typography/demo/editable.tsx, packages/design/src/typography/index.md
- None
| copyable | editable in Modal |
| ![image](https://github.com/user-attachments/assets/12d8224c-12a6-4c4e-a58f-6a5815233420) | ![image](https://github.com/user-attachments/assets/e91cf6c5-eb8d-403e-8baa-c4a6851393cc) |
| 🇨🇳 Chinese | - 📖 Typography 新增可复制和在 Modal 中编辑的示例。          |
=> chore(design): Add copyable and editable demo for Typography

packages/design/src/table/index.$tab-design.md
- None
| 🇨🇳 Chinese | - 📖 Table 设计文档新增 `高亮显式` 规范。         |
=> chore(docs): Update Table design docs

packages/design/src/alert/index.tsx
- None
| ![image](https://github.com/user-attachments/assets/aef43e75-da46-4be3-bede-1742f5b8e7b9) | ![image](https://github.com/user-attachments/assets/d7c42d58-a6db-4565-89e1-b9257dd85d65) |
| 🇨🇳 Chinese | - 💄 Alert 改为使用线性图标，以对齐最新的设计规范。          |
=> improve(design): Alert use outlined icon

packages/ui/src/SideTip/Dragger.tsx, packages/ui/src/SideTip/demo/draggable.tsx, packages/ui/src/SideTip/index.md, packages/ui/src/SideTip/index.tsx
| 🇺🇸 English |     The SideTip component supports disabling the drag functionality.      |
| 🇨🇳 Chinese |      SideTip 组件支持通过关闭拖拽功能     |
=> [feat]: SideTip supports disabling the drag functionality

packages/ui/package.json, pnpm-lock.yaml
- @oceanbase/ui@0.4.11
| 🇨🇳 Chinese |           |
=> chore: Publish 0.4.11

packages/ui/src/BasicLayout/Header.tsx, packages/ui/src/BasicLayout/demo/basic.tsx, packages/ui/src/BasicLayout/index.md, packages/ui/src/BasicLayout/locale/en-US.ts, packages/ui/src/BasicLayout/locale/zh-CN.ts, packages/ui/src/BasicLayout/locale/zh-TW.ts
| :--- | :---|
| ![image](https://github.com/user-attachments/assets/fb7eee2e-7215-4c79-b022-80527ae2c0a4) | ![image](https://github.com/user-attachments/assets/4b98f8bc-5397-4c02-b563-dffe4739be79) |
| 🇺🇸 English | Add versionNotice to BasicLayout     |
| 🇨🇳 Chinese | BasicLayout顶部导航栏增加版本公告属性 |
=> feat(ui): [BasicLayout] add versionNoticePath to BasicLayout

packages/ui/src/DateRanger/PickerPanel.tsx
使用[antd内置api](https://ant.design/components/date-picker#date-picker-demo-mask)实现 日期/时间 输入内容自动选择
| 🇺🇸 English | use `mask` format to auto align date and time format.          |
| 🇨🇳 Chinese |  日期格式改为 `mask`，自动对齐日期和时间格式。       |
=> feat(ui): [date-ranger] use mask format to auto select date/time input content

packages/ui/src/DateRanger/PickerPanel.tsx
交互调整：
| 🇺🇸 English |   Adjust date panel selection interaction        |
| 🇨🇳 Chinese |  💄 优化日期选择面板交互，降低二次选择的复杂性和视觉干扰。         |
=> feat(ui): [date-ranger] use new select ux

packages/design/src/dropdown/demo/dropdown-button.tsx
=> chore(design): Dropdown button demo

.dumirc.ts, packages/design/src/anchor/demo/basic.tsx, packages/design/src/anchor/demo/horizontal.tsx, packages/design/src/anchor/index.md
- None
| 🇨🇳 Chinese | - 📖 新增 Anchor 的文档和示例。          |
=> docs(design): Add docs and demo for Anchor

.dumirc.ts, packages/design/src/anchor/index.md, packages/design/src/steps/demo/basic.tsx, packages/design/src/steps/demo/clickable.tsx, packages/design/src/steps/demo/inline.tsx, packages/design/src/steps/demo/navigation.tsx, packages/design/src/steps/demo/progress-dot.tsx, packages/design/src/steps/demo/vertical.tsx, packages/design/src/steps/index.md
- None
| 🇨🇳 Chinese | - 📖 新增 Steps 的文档和示例。          |
=> docs(design): Add docs and demo for Steps

.dumi/theme/common/styles/Markdown.tsx, packages/design/src/form/demo/form-item-tooltip.tsx, packages/design/src/form/demo/layout.tsx, packages/design/src/form/demo/multiple-layout.tsx, packages/design/src/form/index.md, packages/design/src/form/index.tsx, packages/design/src/form/style/index.ts, packages/design/src/tree-select/index.tsx
- None
| ![image](https://github.com/user-attachments/assets/07444b5e-ad80-45f6-a317-dbc0280f35cf) | ![image](https://github.com/user-attachments/assets/0c7d1841-7bde-4d96-9a41-c742aa0641f4) |
| 🇨🇳 Chinese | - 💄 Form.Item `extra` 提示信息设置 `margin-top` 为 4px。         |
=> improve(design): Form item extra add margin-top style

packages/design/src/form/style/index.ts
- Fix #1025 to avoid shrink.
| ![image](https://github.com/user-attachments/assets/07444b5e-ad80-45f6-a317-dbc0280f35cf) | ![image](https://github.com/user-attachments/assets/0c7d1841-7bde-4d96-9a41-c742aa0641f4) |
| ![image](https://github.com/user-attachments/assets/1a79108d-02bd-478e-a3e4-8dfd9165e2ec) | ![image](https://github.com/user-attachments/assets/7b12ccad-db04-451e-9931-c1a150afc7f5) |
| 🇨🇳 Chinese | - 💄 Form.Item 提示信息的上间距设为 4px。         |
=> improve(design): Form.Item additional text add margin-top style

.dumirc.ts, .fatherrc.base.ts, package.json, packages/design/package.json, packages/design/src/empty/demo/tab-switch.tsx, packages/design/src/empty/index.md, pnpm-lock.yaml
- None
- If multiple Empty component exists in same page, svg id conflicts.
| [Image] | [Image] |
| 🇨🇳 Chinese | - 🐞 修复多个 Empty 同时出现时 svg id 冲突导致插图展示异常的问题。          |
=> fix(design): Use react-inline-svg-unique-id to fix Empty svg id conflicts

packages/ui/src/Action/Group.tsx, packages/ui/src/Action/Item.tsx, packages/ui/src/Action/demo/button.tsx, packages/ui/src/Action/demo/link.tsx, packages/ui/src/Action/index.md
- None
| Action.Button | Action.Link |
| ![image](https://github.com/user-attachments/assets/ed51a2a1-89cf-47d1-9ccd-94a261eb261a) | ![image](https://github.com/user-attachments/assets/c7e5f7c2-e0aa-4d05-9ed8-d7494715069b) |
| 🇨🇳 Chinese | - 🆕 Action.Button 和 Action.Link 新增 `divider` 属性，用于设置位于下拉菜单内时是否带分割线。          |
=> feat(ui): Action.Button and Action.Link add divider prop

packages/design/src/_util/index.ts, packages/design/src/card/index.tsx, packages/design/src/card/style/index.ts, packages/design/src/table/demo/card-table.tsx, packages/design/src/table/demo/pro-card-table.tsx, packages/ui/src/ProCard/index.tsx, packages/ui/src/ProCard/style/index.ts, vitest.config.ts
- None
| Case 1 | Case 2 |
| ![image](https://github.com/user-attachments/assets/cbb8900c-fb80-4963-a38a-73a73acb813e) | ![image](https://github.com/user-attachments/assets/709b7c96-63d9-4c4b-bbed-cc4a634dd544) |
| 🇨🇳 Chinese | - 💄 优化 Table 在无水平间距卡片内的样式，包括第一列和卡片标题对齐、最后一列和卡片操作区对齐、分页器左右增加间距。          |
=> improve(design): Table padding when Card body horizontal padding is 0

packages/design/src/descriptions/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/descriptions/demo/size.tsx, packages/design/src/descriptions/demo/vertical-bordered.tsx, packages/design/src/descriptions/demo/vertical-single-column.tsx, packages/design/src/descriptions/index.md, packages/design/src/descriptions/index.tsx, packages/design/src/descriptions/style/index.ts
| 多列垂直 | 单列垂直 (可用于只读态表单) |
| ![image](https://github.com/user-attachments/assets/c4a39352-b1a5-42b9-ab40-e97cd87130b9) | ![image](https://github.com/user-attachments/assets/4407cb86-c27d-40f3-8526-2c18e293223e) |
| 🇨🇳 Chinese | - 💄 优化 Descriptions 在垂直布局下的间距，并且多列垂直和单列垂直的间距不同。          |
=> improve(design): Descriptions vertical margin style

packages/design/src/descriptions/demo/content.tsx, packages/design/src/descriptions/hooks/useItems.tsx, packages/design/src/descriptions/style/index.ts
- None
| ![image](https://github.com/user-attachments/assets/d68d6c51-1816-4920-a33a-f337b90fd34c) | ![image](https://github.com/user-attachments/assets/5ad4c524-0ae1-4643-8074-ff6cfac0578d) |
| 🇨🇳 Chinese | - 🐞 修复编辑态的 Typography 在 Descriptions 内被遮挡和没有垂直居中的问题。         |
=> fix(design): editing Typography should align vertical in Descriptions

packages/design/src/table/style/index.ts
- None
| ![image](https://github.com/user-attachments/assets/fb75a8d5-e819-4276-bf60-dcd42831d16a) | ![image](https://github.com/user-attachments/assets/40633c29-f613-4193-aff4-49fe8c0819ac) |
| ![image](https://github.com/user-attachments/assets/aaba9d72-0537-4bdb-85d6-da0e4b62ba9a) | ![image](https://github.com/user-attachments/assets/5d011b52-5555-4b2d-a4e1-14219fe647ca) |
| 🇨🇳 Chinese | - 💄 带边框 Table 的表头改为灰底。          |
=> improve(design): bordered Table header should be gray

packages/design/src/table/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/table/__tests__/index.test.tsx, packages/design/src/table/demo/card-table.tsx, packages/design/src/table/demo/inner-bordered.tsx, packages/design/src/table/demo/pro-card-table.tsx, packages/design/src/table/index.md, packages/design/src/table/index.tsx, packages/design/src/table/style/index.ts
- None
| 🇨🇳 Chinese | - 🆕 Table 新增 `innerBordered` 属性，用于设置内部边框。          |
=> feat(design): Table add innerBordered prop

packages/ui/src/ProTable/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/ProTable/__tests__/index.test.tsx, packages/ui/src/ProTable/demo/bordered.tsx, packages/ui/src/ProTable/demo/inner-bordered.tsx, packages/ui/src/ProTable/index.md, packages/ui/src/ProTable/index.tsx
- #1036
| 🇨🇳 Chinese | -  🆕 ProTable 新增 `innerBordered` 属性，用于设置内部边框。          |
=> feat(ui): ProTable add innerBordered prop

packages/ui/src/Login/LoginForm.tsx, packages/ui/src/Login/demo/component-props.tsx, packages/ui/src/Login/demo/item-props.tsx, packages/ui/src/Login/demo/password-optional.tsx, packages/ui/src/Login/index.less, packages/ui/src/Login/index.md
| `passwordOptional`   | `componentProps` |
| ![image](https://github.com/user-attachments/assets/22def07f-ce3c-49b8-bc14-9c0ff03ca5de) |   ![image](https://github.com/user-attachments/assets/2ade8346-98ff-4299-871e-cec61c70e550)      |
| 🇺🇸 English |   -      |
| 🇨🇳 Chinese |  - 🆕 Login 新增 `passwordOptional` 属性，用于设置是否允许密码为空。- 🆕 Login 新增 `componentProps` 属性，用于设置各个组件属性。  |
=> feat(ui): Login add passwordOptional and componentProps props

packages/ui/src/Boundary/index.less
- None
| ![image](https://github.com/user-attachments/assets/c88baec0-09d4-45de-8dd0-d1390f2fffe2) | ![image](https://github.com/user-attachments/assets/8f050975-e40e-4272-97ad-4352dbb60c44) |
| ![image](https://github.com/user-attachments/assets/c6e362de-2be2-4368-8a42-a58e6aeaccb2) | ![image](https://github.com/user-attachments/assets/6dae268c-0e03-4544-89f6-816de0b1a0ac) |
| 🇨🇳 Chinese | - 💄 优化 Boundary 描述文案的间距和操作按钮的字体颜色。          |
=> improve(ui): Boundary description and button style

docs/ui/ui-CHANGELOG.md
`2024-04-28`
- Login
- 🆕 Login 新增 `passwordOptional` 属性，用于设置是否允许密码为空。[#1046](https://github.com/oceanbase/oceanbase-design/pull/1046) [@linhf123](https://github.com/linhf123)
- 🆕 Login 新增 `componentProps` 属性，用于设置各个组件属性。[#1046](https://github.com/oceanbase/oceanbase-design/pull/1046) [@linhf123](https://github.com/linhf123)
- 🐞 修复 DateRanger `style` 和 `className` 应该仅对根组件生效、不应该对 RangePicker 生效的问题。[#1040](https://github.com/oceanbase/oceanbase-design/pull/1040) [@wzc520pyfm](https://github.com/wzc520pyfm)
- 💄 优化 Boundary 描述文案的间距和操作按钮的字体颜色。[#1047](https://github.com/oceanbase/oceanbase-design/pull/1047)
=> chore(docs): Add changelog for @oceanbase/ui@0.4.13

packages/ui/src/DateRanger/index.less
| 🇺🇸 English | fix drop-menu shadow css priority |
| 🇨🇳 Chinese | 提高dropdown menu 的子应用阴影样式优先级，确保无阴影 |
=> fix(ui): [date-ranger] fix drop-menu shadow css priority

packages/ui/src/Login/index.less
- None
| ![image](https://github.com/user-attachments/assets/2ceaadf7-d069-4850-b458-ef3bf4b7cca5) | ![image](https://github.com/user-attachments/assets/2136f1eb-4634-413b-a673-1adefde3169d) |
| ![image](https://github.com/user-attachments/assets/6d9611e3-b12c-4bb0-b028-6c53ad2c4a9c) | ![image](https://github.com/user-attachments/assets/f5577382-6a7f-417d-97be-e81aa463e5b9) |
| 🇨🇳 Chinese | - 💄 Login 的背景图片居中展示。          |
=> improve(ui): Login bg image should align center

packages/ui/src/DateRanger/index.less
| ![image](https://github.com/user-attachments/assets/d3999eee-bd87-4744-9bbf-94ac0b8bcee4) | ![image](https://github.com/user-attachments/assets/caeb92dd-f112-4f26-91da-3424155d37a0) |
| 🇺🇸 English | - update date-ranger bg color to white |
| 🇨🇳 Chinese | - 💄 将 DateRanger 快捷选项的背景色从透明调整为白色。 |
=> fix(ui): [date-ranger] update bg color to colorBgContainer

packages/design/src/static-function/index.tsx, packages/design/src/theme/style/compact.less, packages/design/src/theme/style/default.less, plugin-theme-less.ts
- Ref: #1096
- None
| 🇨🇳 Chinese | - 💄 更新 `boxShadowTertiary` token 的值。          |
=> improve(design): Update boxShadowTertiary token

packages/design/src/segmented/__tests__/__snapshots__/index.test.tsx.snap, packages/design/src/segmented/demo/badge.tsx, packages/design/src/segmented/index.md, packages/design/src/segmented/index.tsx, packages/design/src/segmented/style/index.ts
| 🇺🇸 English | segmented support set badge for item content |
| 🇨🇳 Chinese | 分段控制器支持展示徽标 |
=> feat(design): [segmented] support badge for item content

packages/design/src/tag/style/index.ts
- None
- None
| 🇨🇳 Chinese |  - 🐞 修复 Tag 设置 `font-size` 样式不生效的问题。         |
=> fix(design): Tag font-size style should work

packages/design/src/modal/Modal.tsx, packages/design/src/modal/__tests__/__snapshots__/modal.test.tsx.snap, packages/design/src/modal/__tests__/modal.test.tsx, packages/design/src/modal/demo/extra.tsx, packages/design/src/modal/index.md, packages/design/src/modal/style/index.ts
- None
| 🇺🇸 English | - 🆕 Modal add `extra` prop to set footer extra content.         |
| 🇨🇳 Chinese | - 🆕 Modal 新增 `extra` 属性，用于设置底部额外内容。          |
=> feat(design): Modal add extra prop

packages/codemod/transforms/__testfixtures__/style-to-token/antd-style.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/antd-style.output.js, packages/codemod/transforms/__tests__/style-to-token.test.ts, packages/codemod/transforms/style-to-token.js
- None
- None
| 🇨🇳 Chinese | - 🆕 `style-to-token` 工具支持改写 antd-style `createStyles`。          |
=> feat(codemod): style-to-token support antd-style createStyles

packages/codemod/README.md, packages/codemod/bin/cli.js, packages/codemod/bin/codemod.ignore
- None
- None
| 🇨🇳 Chinese | - 🆕 新增 `--ignore-config` 命令行参数，用于指定 `ignore` 配置文件。          |
=> feat(codemod): cli add --ignore-config args

packages/ui/src/DateRanger/Ranger.tsx
目前重复点击时间区域，面板会关闭再打开，pr后就不会了：
| 🇺🇸 English |  - 🐞 keep the panel open on repeated clicks |
| 🇨🇳 Chinese | - 🐞 修复 DateRanger 在连续点击时面板会频繁开启、关闭的问题。 |
=> fix(ui): [date-ranger] keep the panel open on repeat clicks

packages/ui/src/DateRanger/PickerPanel.tsx
| 🇺🇸 English |      Fix grammar problems     |
| 🇨🇳 Chinese |  - 🐞 修复 dateRanger `defaultValue` 为空时页面崩溃的问题。  |
=> fix(ui): DateRanger defaultValue maybe undefined

packages/design/src/global.css
| 🇨🇳 Chinese | - ⭐️ 优化自定义字体的加载顺序为 `系统字体 -> 自托管字体 -> 在线字体`，避免发起网络请求。          |
=> improve(design): Adjust custom font load order

packages/design/src/descriptions/demo/debug-typography.tsx, packages/design/src/descriptions/hooks/useItems.tsx, packages/design/src/descriptions/index.md, packages/design/src/descriptions/style/index.ts, packages/design/src/typography/Link.tsx, packages/design/src/typography/Paragraph.tsx, packages/design/src/typography/Text.tsx, packages/design/src/typography/Title.tsx
- None
| <img width="1094" height="236" alt="image" src="https://github.com/user-attachments/assets/23c0cbc0-31db-4166-aa7b-90e327f1b509" /> | <img width="1092" height="256" alt="image" src="https://github.com/user-attachments/assets/6bcb42c7-9122-4122-8c9a-d6f975db4546" /> |
| 🇨🇳 Chinese | - 🐞 修复 Descriptions.Item 子元素为 Typography 时复制 tooltip 位置不正确的问题。        |
=> fix(design): Descriptions.Item wrapping Typography should work correctly

packages/charts/package.json, packages/design/package.json, packages/ui/package.json
- None
- None
| 🇨🇳 Chinese | - 🐞 修复 `sideEffects` 配置问题，以支持 tree shaking。          |
=> fix(build): set correct sideEffects to make tree shaking work

packages/design/src/button/style/index.ts
- None
| <img width="1762" height="1542" alt="image" src="https://github.com/user-attachments/assets/6825f6be-293a-401c-8658-ee77419ed381" /> | <img width="1762" height="1542" alt="image" src="https://github.com/user-attachments/assets/5b3aa1f7-7c87-4d1a-be2e-c9eb2f224b9f" /> |
| 🇨🇳 Chinese | - 💄 去掉 Button 的自定义样式，包括阴影、边框和背景色。         |
=> [v1] improve(design): Remove Buttom custom style

packages/design/src/config-provider/index.tsx, packages/design/src/theme/default.ts
- None
| <img width="1772" height="1622" alt="image" src="https://github.com/user-attachments/assets/f263057c-f825-4d35-b3e6-2871f59a3b7c" /> | <img width="1772" height="1622" alt="image" src="https://github.com/user-attachments/assets/441d318d-3a82-45b9-ac5b-2e67a9b1c3e1" /> |
| 🇨🇳 Chinese | - 💄 调整 Tabs 的字体颜色和火柴棍长度。         |
=> [v1] improve(design): Adjust Tabs font color and inkbar width 

packages/design/src/tabs/index.tsx
- None
- None
| 🇨🇳 Chinese | - 🐞 修复 Tabs `ref` 不生效的问题。          |
=> fix(design): Tabs ref should work

packages/design/src/typography/index.md, packages/design/src/typography/style/index.ts
…
- None
- None
| 🇨🇳 Chinese | - 🐞 修复 Typography Text 和 Paragraph 类名样式 (行高、字体颜色和大小) 不生效的问题。     |
=> fix(design): Typography Text and Paragraph className should work about line-height, color and font-size

packages/codemod/README.md, packages/codemod/transforms/__testfixtures__/style-to-token/antd-style.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/antd-style.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/block-statement.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/block-statement.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/class-component.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/class-component.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/existed-useToken.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/existed-useToken.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/function-component.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/function-component.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/function.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/function.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/hooks.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/hooks.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/nested-block-statement.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/nested-block-statement.output.js, packages/codemod/transforms/__testfixtures__/style-to-token/top-identifier.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/top-identifier.output.js, packages/codemod/transforms/style-to-token.js, packages/codemod/transforms/utils/token.js
- None
- React function components:
```diff
import React from 'react';
- import { Alert, Button } from '@oceanbase/design';
+ import { Alert, Button, theme } from '@oceanbase/design';
const Demo = () => {
+   const { token } = theme.useToken();
return (
-     <div>
-       <Alert style={{ fontSize: 14 }} />
-       <Button style={{ fontSize: 12 }}></Button>
-     </div>
+     <div>
+       <Alert style={{ fontSize: token.fontSize }} />
+       <Button style={{ fontSize: token.fontSizeSM }}></Button>
+     </div>
);
};
export default Demo;
```
- React class components:
```diff
import React from 'react';
- import { Alert, Button } from '@oceanbase/design';
+ import { Alert, Button, token } from '@oceanbase/design';
class Demo extends React.PureComponent {
constructor(props) {
super(props); …
```
=> feat(codemod): style-to-token support to rewrite fontSize token

packages/design/src/theme/index.md, packages/ui/src/DateRanger/index.less, packages/ui/src/GraphToolbar/index.less, packages/ui/src/Highlight/index.less
- #1183
- None
| 🇨🇳 Chinese | - 🐞 修复 DateRanger、GraphToolbar 和 Highlight 圆角样式不生效的问题。          |
=> [v1] fix(ui): ~@{borderRadius}px => @borderradius for less token usage

packages/codemod/transforms/__testfixtures__/style-to-token/anonymous-function.input.js, packages/codemod/transforms/__testfixtures__/style-to-token/anonymous-function.output.js, packages/codemod/transforms/__tests__/style-to-token.test.ts, packages/codemod/transforms/style-to-token.js
- None
- None
| 🇨🇳 Chinese | - ⭐️ 优化 `style-to-token` 对匿名函数组件的改写结果。          |
=> [v1] improve(codemod): style-to-token for anonymous function component

packages/design/src/theme/default.ts, packages/design/src/theme/style/aliyun.less, packages/design/src/theme/style/compact.less, packages/design/src/theme/style/dark.less, packages/design/src/theme/style/default.less
- None
- None
| 🇨🇳 Chinese | - 🌈 更新 Design Token `controlHeight` 的值 `32` => `28`           |
=> [v1] improve(design): 32 => 28 for controlHeight design token

packages/design/src/theme/default.ts
| <img width="1682" height="264" alt="image" src="https://github.com/user-attachments/assets/3d0288ea-9f6f-4f0f-9955-aa2be00214fe" /> | <img width="1684" height="304" alt="image" src="https://github.com/user-attachments/assets/01f37a15-629b-4454-9e41-d1a057f1647c" /> |
| 🇨🇳 Chinese | - 💄 优化 Skeleton 的骨架屏圆角。          |
=> [v1] improve(design): Skeleton block radius change to 4

packages/ui/src/ProCard/demo/basic.tsx, packages/ui/src/ProCard/index.tsx
- None
| <img width="664" height="440" alt="image" src="https://github.com/user-attachments/assets/2474cd31-c9b5-4c6b-9b4e-565e16237ff2" /> | <img width="662" height="414" alt="image" src="https://github.com/user-attachments/assets/16685796-dab7-4b0e-a1c1-10bb46d49199" /> |
| 🇨🇳 Chinese | - 🐞 修复 ProCard 加载态骨架屏和 Card 不一致的问题。          |
=> [v1] fix(ui): ProCard loading skeleton should be same with Card

packages/design/src/badge/demo/status-inner.tsx, packages/design/src/badge/index.md, packages/design/src/badge/style/index.ts
- None
| <img width="1658" height="716" alt="image" src="https://github.com/user-attachments/assets/8dca312a-b49b-4c57-aa64-40b620fd5554" /> | <img width="1652" height="704" alt="image" src="https://github.com/user-attachments/assets/c87610e3-1389-437a-a503-de5bea9e7a84" /> |
| 🇨🇳 Chinese | - 🐞 修复 Badge 状态文本字体大小不会继承父元素的问题，便于和其他组件组合使用。          |
=> [v1] fix(design): Badge status text font-size should inherit from parent

packages/design/src/table/style/index.ts, packages/ui/src/ProTable/index.tsx
- None
| <img width="1662" height="1354" alt="image" src="https://github.com/user-attachments/assets/9df7f90f-dfcb-421c-a0ee-8bbdb42e9281" /> | <img width="1662" height="1302" alt="image" src="https://github.com/user-attachments/assets/625fbae7-29c2-49dc-a9b6-30c32a02cce8" /> |
| 🇨🇳 Chinese | - 🐞 修复 ProTable 卡片底部间距过大的问题。          |
=> fix(ui): ProTable cardProps.bodyStyle.paddingBlock should be 0

packages/design/src/theme/default.ts
- None
| <img width="602" height="964" alt="image" src="https://github.com/user-attachments/assets/ec60d702-f387-4bfb-95f0-340dad97bd2a" /> | <img width="602" height="962" alt="image" src="https://github.com/user-attachments/assets/cbc67fdd-7182-4d4c-8b1b-2f5645dc7e10" /> |
| 🇨🇳 Chinese | - 🌈 更新 Menu `groupTitleColor` 分组标题颜色 `#8592AD` => `#5C6B8A`。          |
=> [v1] improve(design): Update Menu.groupTitleColor design token to #5C6B8A
